//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum BookableResourceBookingState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Representa os detalhes de linha de uma reserva de recurso.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bookableresourcebooking")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class BookableResourceBooking : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string BookableResourceBookingId = "bookableresourcebookingid";
			public const string Id = "bookableresourcebookingid";
			public const string BookingStatus = "bookingstatus";
			public const string BookingType = "bookingtype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Duration = "duration";
			public const string EndTime = "endtime";
			public const string ExchangeRate = "exchangerate";
			public const string Header = "header";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_AcceptCascadeCrewChanges = "msdyn_acceptcascadecrewchanges";
			public const string msdyn_ActualArrivalTime = "msdyn_actualarrivaltime";
			public const string msdyn_ActualTravelDuration = "msdyn_actualtravelduration";
			public const string msdyn_AllowOverlapping = "msdyn_allowoverlapping";
			public const string msdyn_AppointmentBookingId = "msdyn_appointmentbookingid";
			public const string msdyn_BookingMethod = "msdyn_bookingmethod";
			public const string msdyn_BookingSetupMetadataId = "msdyn_bookingsetupmetadataid";
			public const string msdyn_CascadeCrewChanges = "msdyn_cascadecrewchanges";
			public const string msdyn_effort = "msdyn_effort";
			public const string msdyn_EstimatedArrivalTime = "msdyn_estimatedarrivaltime";
			public const string msdyn_EstimatedTravelDuration = "msdyn_estimatedtravelduration";
			public const string msdyn_Latitude = "msdyn_latitude";
			public const string msdyn_Longitude = "msdyn_longitude";
			public const string msdyn_MilesTraveled = "msdyn_milestraveled";
			public const string msdyn_projectid = "msdyn_projectid";
			public const string msdyn_projectteamid = "msdyn_projectteamid";
			public const string msdyn_requirementgroupid = "msdyn_requirementgroupid";
			public const string msdyn_resourcecategoryid = "msdyn_resourcecategoryid";
			public const string msdyn_ResourceGroup = "msdyn_resourcegroup";
			public const string msdyn_ResourceRequirement = "msdyn_resourcerequirement";
			public const string msdyn_TimeGroupDetailSelected = "msdyn_timegroupdetailselected";
			public const string msdyn_URSInternalFlags = "msdyn_ursinternalflags";
			public const string msdyn_WorkLocation = "msdyn_worklocation";
			public const string Name = "name";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ProcessId = "processid";
			public const string Resource = "resource";
			public const string smt_tx_description = "smt_tx_description";
			public const string StageId = "stageid";
			public const string StartTime = "starttime";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bookingstatus_bookableresourcebooking_BookingStatus = "bookingstatus_bookableresourcebooking_BookingStatus";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceBooking() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bookableresourcebooking";
		
		public const string EntitySchemaName = "BookableResourceBooking";
		
		public const string PrimaryIdAttribute = "bookableresourcebookingid";
		
		public const string PrimaryNameAttribute = "name";
		
		public const int EntityTypeCode = 1145;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da reserva do recurso.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcebookingid")]
		public System.Nullable<System.Guid> BookableResourceBookingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bookableresourcebookingid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceBookingId");
				this.SetAttributeValue("bookableresourcebookingid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("BookableResourceBookingId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcebookingid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.BookableResourceBookingId = value;
			}
		}
		
		/// <summary>
		/// Selecione o status da reserva.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingstatus")]
		public Microsoft.Xrm.Sdk.EntityReference BookingStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bookingstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookingStatus");
				this.SetAttributeValue("bookingstatus", value);
				this.OnPropertyChanged("BookingStatus");
			}
		}
		
		/// <summary>
		/// Selecione se a reserva é sólida ou líquida. Reservas sólidas são confirmadas e não podem ser alteradas; reservas líquidas podem ser alteradas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingtype")]
		public Microsoft.Xrm.Sdk.OptionSetValue BookingType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("bookingtype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookingType");
				this.SetAttributeValue("bookingtype", value);
				this.OnPropertyChanged("BookingType");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que criou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedBy");
				this.SetAttributeValue("createdby", value);
				this.OnPropertyChanged("CreatedBy");
			}
		}
		
		/// <summary>
		/// Data e hora de criação do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOn");
				this.SetAttributeValue("createdon", value);
				this.OnPropertyChanged("CreatedOn");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que criou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Insira a duração da reserva.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duration")]
		public System.Nullable<int> Duration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("duration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Duration");
				this.SetAttributeValue("duration", value);
				this.OnPropertyChanged("Duration");
			}
		}
		
		/// <summary>
		/// Insira a data e hora de término da reserva.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("endtime")]
		public System.Nullable<System.DateTime> EndTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("endtime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EndTime");
				this.SetAttributeValue("endtime", value);
				this.OnPropertyChanged("EndTime");
			}
		}
		
		/// <summary>
		/// Taxa de câmbio da moeda associada ao bookableresourcebooking em relação à moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ExchangeRate");
				this.SetAttributeValue("exchangerate", value);
				this.OnPropertyChanged("ExchangeRate");
			}
		}
		
		/// <summary>
		/// Mostra a referência ao registro do cabeçalho de reserva que representa o resumo de reservas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("header")]
		public Microsoft.Xrm.Sdk.EntityReference Header
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("header");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Header");
				this.SetAttributeValue("header", value);
				this.OnPropertyChanged("Header");
			}
		}
		
		/// <summary>
		/// Número de sequência da importação que criou este registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que modificou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedBy");
				this.SetAttributeValue("modifiedby", value);
				this.OnPropertyChanged("ModifiedBy");
			}
		}
		
		/// <summary>
		/// Data e hora de modificação do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOn");
				this.SetAttributeValue("modifiedon", value);
				this.OnPropertyChanged("ModifiedOn");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que modificou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Define se esta reserva aceita alterações propagadas como alterações em cascata
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_acceptcascadecrewchanges")]
		public System.Nullable<bool> msdyn_AcceptCascadeCrewChanges
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_acceptcascadecrewchanges");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AcceptCascadeCrewChanges");
				this.SetAttributeValue("msdyn_acceptcascadecrewchanges", value);
				this.OnPropertyChanged("msdyn_AcceptCascadeCrewChanges");
			}
		}
		
		/// <summary>
		/// Mostra a hora em que o trabalho começou.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_actualarrivaltime")]
		public System.Nullable<System.DateTime> msdyn_ActualArrivalTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualarrivaltime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ActualArrivalTime");
				this.SetAttributeValue("msdyn_actualarrivaltime", value);
				this.OnPropertyChanged("msdyn_ActualArrivalTime");
			}
		}
		
		/// <summary>
		/// Mostra a duração total da viagem. Se você deixar este campo em branco, o sistema determinará automaticamente a duração da viagem, calculando detalhes do diário de recursos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_actualtravelduration")]
		public System.Nullable<int> msdyn_ActualTravelDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_actualtravelduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ActualTravelDuration");
				this.SetAttributeValue("msdyn_actualtravelduration", value);
				this.OnPropertyChanged("msdyn_ActualTravelDuration");
			}
		}
		
		/// <summary>
		/// Permite a exibição da hora desta reserva no assistente de agendamento, conforme disponível.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_allowoverlapping")]
		public System.Nullable<bool> msdyn_AllowOverlapping
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_allowoverlapping");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AllowOverlapping");
				this.SetAttributeValue("msdyn_allowoverlapping", value);
				this.OnPropertyChanged("msdyn_AllowOverlapping");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do Compromisso associado à Reserva de Recursos Reserváveis.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_appointmentbookingid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_AppointmentBookingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_appointmentbookingid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AppointmentBookingId");
				this.SetAttributeValue("msdyn_appointmentbookingid", value);
				this.OnPropertyChanged("msdyn_AppointmentBookingId");
			}
		}
		
		/// <summary>
		/// Mostra o método usado para criar esta reserva.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingmethod")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_BookingMethod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_bookingmethod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BookingMethod");
				this.SetAttributeValue("msdyn_bookingmethod", value);
				this.OnPropertyChanged("msdyn_BookingMethod");
			}
		}
		
		/// <summary>
		/// Um identificador exclusivo para os metadados da configuração da reserva que estão associados a uma reserva de recurso reservável.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingsetupmetadataid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_BookingSetupMetadataId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_bookingsetupmetadataid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BookingSetupMetadataId");
				this.SetAttributeValue("msdyn_bookingsetupmetadataid", value);
				this.OnPropertyChanged("msdyn_BookingSetupMetadataId");
			}
		}
		
		/// <summary>
		/// Define se a alteração de um dos campos a seguir (Hora de Início, Hora de Término, Status) deve propagar as alterações para outras reservas neste requisito que tenham as mesmas horas de início e de término.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_cascadecrewchanges")]
		public System.Nullable<bool> msdyn_CascadeCrewChanges
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_cascadecrewchanges");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_CascadeCrewChanges");
				this.SetAttributeValue("msdyn_cascadecrewchanges", value);
				this.OnPropertyChanged("msdyn_CascadeCrewChanges");
			}
		}
		
		/// <summary>
		/// Capacidade que é necessário tirar da capacidade do recurso
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_effort")]
		public System.Nullable<decimal> msdyn_effort
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("msdyn_effort");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_effort");
				this.SetAttributeValue("msdyn_effort", value);
				this.OnPropertyChanged("msdyn_effort");
			}
		}
		
		/// <summary>
		/// Hora de Chegada Estimada
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedarrivaltime")]
		public System.Nullable<System.DateTime> msdyn_EstimatedArrivalTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_estimatedarrivaltime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_EstimatedArrivalTime");
				this.SetAttributeValue("msdyn_estimatedarrivaltime", value);
				this.OnPropertyChanged("msdyn_EstimatedArrivalTime");
			}
		}
		
		/// <summary>
		/// Duração Estimada da Viagem
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedtravelduration")]
		public System.Nullable<int> msdyn_EstimatedTravelDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_estimatedtravelduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_EstimatedTravelDuration");
				this.SetAttributeValue("msdyn_estimatedtravelduration", value);
				this.OnPropertyChanged("msdyn_EstimatedTravelDuration");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_latitude")]
		public System.Nullable<double> msdyn_Latitude
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_latitude");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Latitude");
				this.SetAttributeValue("msdyn_latitude", value);
				this.OnPropertyChanged("msdyn_Latitude");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_longitude")]
		public System.Nullable<double> msdyn_Longitude
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_longitude");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Longitude");
				this.SetAttributeValue("msdyn_longitude", value);
				this.OnPropertyChanged("msdyn_Longitude");
			}
		}
		
		/// <summary>
		/// Neste campo, você pode inserir o total de quilômetros percorridos pelo recurso até o local de trabalho
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_milestraveled")]
		public System.Nullable<double> msdyn_MilesTraveled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_milestraveled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_MilesTraveled");
				this.SetAttributeValue("msdyn_milestraveled", value);
				this.OnPropertyChanged("msdyn_MilesTraveled");
			}
		}
		
		/// <summary>
		/// Projeto do registro de detalhes da reserva
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_projectid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_projectid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_projectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_projectid");
				this.SetAttributeValue("msdyn_projectid", value);
				this.OnPropertyChanged("msdyn_projectid");
			}
		}
		
		/// <summary>
		/// Membro da equipe de projeto do registro de detalhes da reserva
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_projectteamid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_projectteamid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_projectteamid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_projectteamid");
				this.SetAttributeValue("msdyn_projectteamid", value);
				this.OnPropertyChanged("msdyn_projectteamid");
			}
		}
		
		/// <summary>
		/// Grupo de Requisitos
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_requirementgroupid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_requirementgroupid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_requirementgroupid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_requirementgroupid");
				this.SetAttributeValue("msdyn_requirementgroupid", value);
				this.OnPropertyChanged("msdyn_requirementgroupid");
			}
		}
		
		/// <summary>
		/// Categoria de Recurso
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcecategoryid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_resourcecategoryid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcecategoryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_resourcecategoryid");
				this.SetAttributeValue("msdyn_resourcecategoryid", value);
				this.OnPropertyChanged("msdyn_resourcecategoryid");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do Recurso associado à Reserva de Recurso
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcegroup")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ResourceGroup
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcegroup");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ResourceGroup");
				this.SetAttributeValue("msdyn_resourcegroup", value);
				this.OnPropertyChanged("msdyn_ResourceGroup");
			}
		}
		
		/// <summary>
		/// Requisito de Recurso
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcerequirement")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ResourceRequirement
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcerequirement");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ResourceRequirement");
				this.SetAttributeValue("msdyn_resourcerequirement", value);
				this.OnPropertyChanged("msdyn_ResourceRequirement");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_timegroupdetailselected")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_TimeGroupDetailSelected
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_timegroupdetailselected");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TimeGroupDetailSelected");
				this.SetAttributeValue("msdyn_timegroupdetailselected", value);
				this.OnPropertyChanged("msdyn_TimeGroupDetailSelected");
			}
		}
		
		/// <summary>
		/// Somente para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_ursinternalflags")]
		public string msdyn_URSInternalFlags
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_ursinternalflags");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_URSInternalFlags");
				this.SetAttributeValue("msdyn_ursinternalflags", value);
				this.OnPropertyChanged("msdyn_URSInternalFlags");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_worklocation")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_WorkLocation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_worklocation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_WorkLocation");
				this.SetAttributeValue("msdyn_worklocation", value);
				this.OnPropertyChanged("msdyn_WorkLocation");
			}
		}
		
		/// <summary>
		/// Digite um nome para a reserva.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Data e hora da migração do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// ID do Proprietário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da unidade de negócios proprietária do registro
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da equipe que possui o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário proprietário do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Contém a id do processo associado à entidade.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		/// <summary>
		/// Mostra o recurso que está reservado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resource")]
		public Microsoft.Xrm.Sdk.EntityReference Resource
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("resource");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Resource");
				this.SetAttributeValue("resource", value);
				this.OnPropertyChanged("Resource");
			}
		}
		
		/// <summary>
		/// Campo para anotações nas Reservas do Recurso.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_tx_description")]
		public string smt_tx_description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("smt_tx_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("smt_tx_description");
				this.SetAttributeValue("smt_tx_description", value);
				this.OnPropertyChanged("smt_tx_description");
			}
		}
		
		/// <summary>
		/// Contém a id do estágio onde a entidade está localizada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// Insira a data e hora de início da reserva.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("starttime")]
		public System.Nullable<System.DateTime> StartTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("starttime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StartTime");
				this.SetAttributeValue("starttime", value);
				this.OnPropertyChanged("StartTime");
			}
		}
		
		/// <summary>
		/// Status da Reserva do Recurso Reservável
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<CrmEarlyBound.BookableResourceBookingState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((CrmEarlyBound.BookableResourceBookingState)(System.Enum.ToObject(typeof(CrmEarlyBound.BookableResourceBookingState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Motivo do status da Reserva do Recurso Reservável
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Taxa de câmbio da moeda associada ao BookableResourceBooking em relação à moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Uma lista separada por vírgula de valores de cadeia de caracteres representando os identificadores exclusivos dos estágios de uma instância do fluxo do processo empresarial na ordem em que ocorrem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Código de fuso horário em uso quando o registro foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Número da Versão
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("VersionNumber");
				this.SetAttributeValue("versionnumber", value);
				this.OnPropertyChanged("VersionNumber");
			}
		}
		
		/// <summary>
		/// N:1 bookingstatus_bookableresourcebooking_BookingStatus
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingstatus")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookingstatus_bookableresourcebooking_BookingStatus")]
		public CrmEarlyBound.BookingStatus bookingstatus_bookableresourcebooking_BookingStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.BookingStatus>("bookingstatus_bookableresourcebooking_BookingStatus", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookingstatus_bookableresourcebooking_BookingStatus");
				this.SetRelatedEntity<CrmEarlyBound.BookingStatus>("bookingstatus_bookableresourcebooking_BookingStatus", null, value);
				this.OnPropertyChanged("bookingstatus_bookableresourcebooking_BookingStatus");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceBooking(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["bookableresourcebookingid"] = base.Id;
                        break;
                    case "bookableresourcebookingid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingtype")]
		//public virtual bookableresourcebooking_bookingtype? BookingTypeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((bookableresourcebooking_bookingtype?)(EntityOptionSetEnum.GetEnum(this, "bookingtype")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		BookingType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingmethod")]
		//public virtual msdyn_resourceschedulesource? msdyn_BookingMethodEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((msdyn_resourceschedulesource?)(EntityOptionSetEnum.GetEnum(this, "msdyn_bookingmethod")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		msdyn_BookingMethod = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_worklocation")]
		//public virtual msdyn_worklocation? msdyn_WorkLocationEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((msdyn_worklocation?)(EntityOptionSetEnum.GetEnum(this, "msdyn_worklocation")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		msdyn_WorkLocation = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		//public virtual bookableresourcebooking_statuscode? StatusCodeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((bookableresourcebooking_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
	}
}