//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public enum msdyn_timeentry_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Ativoa = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inativoa = 2,
	}
}