//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Pixeon.Extends.Earlybound
{

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
    public enum msdyn_organizationalunitState
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
    }

    /// <summary>
    /// Divisão da empresa ou da organização que tem uma lista de preços de custo específica associada a ela.
    /// </summary>
    [System.Runtime.Serialization.DataContractAttribute()]
    [Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_organizationalunit")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
    public partial class msdyn_organizationalunit : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
    {

        public static class Fields
        {
            public const string CreatedBy = "createdby";
            public const string CreatedOn = "createdon";
            public const string CreatedOnBehalfBy = "createdonbehalfby";
            public const string ImportSequenceNumber = "importsequencenumber";
            public const string ModifiedBy = "modifiedby";
            public const string ModifiedOn = "modifiedon";
            public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
            public const string msdyn_currency = "msdyn_currency";
            public const string msdyn_description = "msdyn_description";
            public const string msdyn_Latitude = "msdyn_latitude";
            public const string msdyn_Longitude = "msdyn_longitude";
            public const string msdyn_name = "msdyn_name";
            public const string msdyn_organizationalunitId = "msdyn_organizationalunitid";
            public const string Id = "msdyn_organizationalunitid";
            public const string OrganizationId = "organizationid";
            public const string OverriddenCreatedOn = "overriddencreatedon";
            public const string StateCode = "statecode";
            public const string StatusCode = "statuscode";
            public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
            public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
            public const string VersionNumber = "versionnumber";
            public const string smt_bt_channel = "smt_bt_channel";
            public const string smt_st_domain = "smt_st_domain";

        }

        /// <summary>
        /// Default Constructor.
        /// </summary>
        public msdyn_organizationalunit() :
                base(EntityLogicalName)
        {
        }

        public const string EntityLogicalName = "msdyn_organizationalunit";

        public const string PrimaryIdAttribute = "msdyn_organizationalunitid";

        public const string PrimaryNameAttribute = "msdyn_name";

        public const int EntityTypeCode = 10036;

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

        private void OnPropertyChanged(string propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        private void OnPropertyChanging(string propertyName)
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
            }
        }

        /// <summary>
        /// Identificador exclusivo do usuário que criou o registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
            }
        }

        /// <summary>
        /// Data e hora de criação do registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
        public System.Nullable<System.DateTime> CreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
            }
        }

        /// <summary>
        /// Identificador exclusivo do usuário delegado que criou o registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
            }
            set
            {
                this.OnPropertyChanging("CreatedOnBehalfBy");
                this.SetAttributeValue("createdonbehalfby", value);
                this.OnPropertyChanged("CreatedOnBehalfBy");
            }
        }

        /// <summary>
        /// Número da Sequência da Importação que criou este registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
        public System.Nullable<int> ImportSequenceNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
            }
            set
            {
                this.OnPropertyChanging("ImportSequenceNumber");
                this.SetAttributeValue("importsequencenumber", value);
                this.OnPropertyChanged("ImportSequenceNumber");
            }
        }

        /// <summary>
        /// Identificador exclusivo do usuário que modificou o registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
            }
        }

        /// <summary>
        /// Data e hora de modificação do registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
        public System.Nullable<System.DateTime> ModifiedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
            }
        }

        /// <summary>
        /// Identificador exclusivo do usuário delegado que modificou o registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
        public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
            }
            set
            {
                this.OnPropertyChanging("ModifiedOnBehalfBy");
                this.SetAttributeValue("modifiedonbehalfby", value);
                this.OnPropertyChanged("ModifiedOnBehalfBy");
            }
        }

        /// <summary>
        /// Selecione a moeda usada pela organização para rastrear seus custos.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_currency")]
        public Microsoft.Xrm.Sdk.EntityReference msdyn_currency
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_currency");
            }
            set
            {
                this.OnPropertyChanging("msdyn_currency");
                this.SetAttributeValue("msdyn_currency", value);
                this.OnPropertyChanged("msdyn_currency");
            }
        }

        /// <summary>
        /// Selecione a moeda usada pela organização para rastrear seus custos.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_currency")]
        public Microsoft.Xrm.Sdk.EntityReference smt_equipedaunidade
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("smt_equipedaunidade");
            }
            set
            {
                this.OnPropertyChanging("smt_equipedaunidade");
                this.SetAttributeValue("smt_equipedaunidade", value);
                this.OnPropertyChanged("smt_equipedaunidade");
            }
        }
        

        /// <summary>
        /// Insira uma descrição da unidade organizacional.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_description")]
        public string msdyn_description
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_description");
            }
            set
            {
                this.OnPropertyChanging("msdyn_description");
                this.SetAttributeValue("msdyn_description", value);
                this.OnPropertyChanged("msdyn_description");
            }
        }

        /// <summary>
        /// A latitude a ser usada para o local da unidade organizacional.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_latitude")]
        public System.Nullable<double> msdyn_Latitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_latitude");
            }
            set
            {
                this.OnPropertyChanging("msdyn_Latitude");
                this.SetAttributeValue("msdyn_latitude", value);
                this.OnPropertyChanged("msdyn_Latitude");
            }
        }

        /// <summary>
        /// A longitude a ser usada para o local da unidade organizacional.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_longitude")]
        public System.Nullable<double> msdyn_Longitude
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<double>>("msdyn_longitude");
            }
            set
            {
                this.OnPropertyChanging("msdyn_Longitude");
                this.SetAttributeValue("msdyn_longitude", value);
                this.OnPropertyChanged("msdyn_Longitude");
            }
        }

        /// <summary>
        /// O nome da entidade personalizada.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
        public string msdyn_name
        {
            get
            {
                return this.GetAttributeValue<string>("msdyn_name");
            }
            set
            {
                this.OnPropertyChanging("msdyn_name");
                this.SetAttributeValue("msdyn_name", value);
                this.OnPropertyChanged("msdyn_name");
            }
        }

        /// <summary>
        /// Identificador exclusivo de instâncias da entidade
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_organizationalunitid")]
        public System.Nullable<System.Guid> msdyn_organizationalunitId
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_organizationalunitid");
            }
            set
            {
                this.OnPropertyChanging("msdyn_organizationalunitId");
                this.SetAttributeValue("msdyn_organizationalunitid", value);
                if (value.HasValue)
                {
                    base.Id = value.Value;
                }
                else
                {
                    base.Id = System.Guid.Empty;
                }
                this.OnPropertyChanged("msdyn_organizationalunitId");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_organizationalunitid")]
        public override System.Guid Id
        {
            get
            {
                return base.Id;
            }
            set
            {
                this.msdyn_organizationalunitId = value;
            }
        }

        /// <summary>
        /// Identificador exclusivo da organização
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
        public Microsoft.Xrm.Sdk.EntityReference OrganizationId
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
            }
        }

        /// <summary>
        /// Data e hora da migração do registro.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
        public System.Nullable<System.DateTime> OverriddenCreatedOn
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
            }
            set
            {
                this.OnPropertyChanging("OverriddenCreatedOn");
                this.SetAttributeValue("overriddencreatedon", value);
                this.OnPropertyChanged("OverriddenCreatedOn");
            }
        }

        ///// <summary>
        ///// Status da Unidade Organizacional
        ///// </summary>
        //[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        //public System.Nullable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_organizationalunitState> StateCode
        //{
        //    get
        //    {
        //        Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
        //        if ((optionSet != null))
        //        {
        //            return ((CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_organizationalunitState)(System.Enum.ToObject(typeof(CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_organizationalunitState), optionSet.Value)));
        //        }
        //        else
        //        {
        //            return null;
        //        }
        //    }
        //    set
        //    {
        //        this.OnPropertyChanging("StateCode");
        //        if ((value == null))
        //        {
        //            this.SetAttributeValue("statecode", null);
        //        }
        //        else
        //        {
        //            this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
        //        }
        //        this.OnPropertyChanged("StateCode");
        //    }
        //}

        /// <summary>
        /// Razão do status da Unidade Organizacional
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
        public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
            }
            set
            {
                this.OnPropertyChanging("StatusCode");
                this.SetAttributeValue("statuscode", value);
                this.OnPropertyChanged("StatusCode");
            }
        }

        /// <summary>
        /// Somente para uso interno.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
        public System.Nullable<int> TimeZoneRuleVersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
            }
            set
            {
                this.OnPropertyChanging("TimeZoneRuleVersionNumber");
                this.SetAttributeValue("timezoneruleversionnumber", value);
                this.OnPropertyChanged("TimeZoneRuleVersionNumber");
            }
        }

        /// <summary>
        /// Código do fuso horário que estava em uso quando o registro foi criado.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
        public System.Nullable<int> UTCConversionTimeZoneCode
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
            }
            set
            {
                this.OnPropertyChanging("UTCConversionTimeZoneCode");
                this.SetAttributeValue("utcconversiontimezonecode", value);
                this.OnPropertyChanged("UTCConversionTimeZoneCode");
            }
        }

        /// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_bt_channel")]
        public System.Nullable<bool> smt_bt_channel
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<bool>>("smt_bt_channel");
            }
            set
            {
                this.OnPropertyChanging("smt_bt_channel");
                this.SetAttributeValue("smt_bt_channel", value);
                this.OnPropertyChanged("smt_bt_channel");
            }
        }

        /// <summary>
        /// Número da Versão
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
        public System.Nullable<long> VersionNumber
        {
            get
            {
                return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
            }
        }

        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_st_domain")]
        public string smt_st_domain
        {
            get
            {
                return this.GetAttributeValue<string>("smt_st_domain");
            }
            set
            {
                this.OnPropertyChanging("smt_st_domain");
                this.SetAttributeValue("smt_st_domain", value);
                this.OnPropertyChanged("smt_st_domain");
            }
        }
    }
}