//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Smart.ExtendedPSA.Extends.Earlybound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum msdyn_projecttaskstatusindicators
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Green = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Red = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yellow = 192350001,
	}
}