//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Smart.ExtendedPSA.Extends.Earlybound
{
	
	/// <summary>
	/// Item de linha em um pedido de venda.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("salesorderdetail")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class SalesOrderDetail : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public SalesOrderDetail() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "salesorderdetail";
		
		public const string PrimaryIdAttribute = "salesorderdetailid";
		
		public const string PrimaryNameAttribute = "salesorderdetailname";
		
		public const int EntityTypeCode = 1089;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Mostra o preço total do produto da ordem, com base no preço por unidade, desconto por volume e quantidade.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baseamount")]
		public Microsoft.Xrm.Sdk.Money BaseAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("baseamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BaseAmount");
				this.SetAttributeValue("baseamount", value);
				this.OnPropertyChanged("BaseAmount");
			}
		}
		
		/// <summary>
		/// Valor do Valor em moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("baseamount_base")]
		public Microsoft.Xrm.Sdk.Money BaseAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("baseamount_base");
			}
		}
		
		/// <summary>
		/// Mostra quem criou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data e hora de criação do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Mostra quem criou o registro em nome de outro usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Digite informações adicionais para descrever o produto da ordem, como os detalhes de fabricação ou substituições aceitáveis.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Mostra a taxa de conversão da moeda do registro. A taxa de câmbio é usada para converter todos os campos monetários do registro da moeda local na moeda padrão do sistema.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Mostra o valor total devido do produto da ordem, com base na soma do preço unitário, quantidade, descontos e imposto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("extendedamount")]
		public Microsoft.Xrm.Sdk.Money ExtendedAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("extendedamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ExtendedAmount");
				this.SetAttributeValue("extendedamount", value);
				this.OnPropertyChanged("ExtendedAmount");
			}
		}
		
		/// <summary>
		/// Valor do Valor Total em moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("extendedamount_base")]
		public Microsoft.Xrm.Sdk.Money ExtendedAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("extendedamount_base");
			}
		}
		
		/// <summary>
		/// Número de sequência da importação que criou este registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Escolha se o item de linha da fatura é copiado de outro item ou fonte de dados.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscopied")]
		public System.Nullable<bool> IsCopied
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("iscopied");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsCopied");
				this.SetAttributeValue("iscopied", value);
				this.OnPropertyChanged("IsCopied");
			}
		}
		
		/// <summary>
		/// Escolha se o preço por unidade é fixado no valor da lista de preços especificada ou se pode ser substituído pelos usuários que têm direitos de edição no produto da ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispriceoverridden")]
		public System.Nullable<bool> IsPriceOverridden
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ispriceoverridden");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsPriceOverridden");
				this.SetAttributeValue("ispriceoverridden", value);
				this.OnPropertyChanged("IsPriceOverridden");
			}
		}
		
		/// <summary>
		/// Escolha se o produto existe no catálogo de produtos do Microsoft Dynamics 365 ou se é um produto fora do catálogo específico à ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isproductoverridden")]
		public System.Nullable<bool> IsProductOverridden
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isproductoverridden");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsProductOverridden");
				this.SetAttributeValue("isproductoverridden", value);
				this.OnPropertyChanged("IsProductOverridden");
			}
		}
		
		/// <summary>
		/// Digite o número do item de linha do produto da ordem para identificar facilmente o produto na ordem e garantir que ele seja listado na sequência correta.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lineitemnumber")]
		public System.Nullable<int> LineItemNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("lineitemnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("LineItemNumber");
				this.SetAttributeValue("lineitemnumber", value);
				this.OnPropertyChanged("LineItemNumber");
			}
		}
		
		/// <summary>
		/// Digite o valor do desconto manual do produto da ordem para deduzir qualquer economia negociada ou outra economia do total do produto na ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("manualdiscountamount")]
		public Microsoft.Xrm.Sdk.Money ManualDiscountAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("manualdiscountamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ManualDiscountAmount");
				this.SetAttributeValue("manualdiscountamount", value);
				this.OnPropertyChanged("ManualDiscountAmount");
			}
		}
		
		/// <summary>
		/// Valor do Desconto Manual em moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("manualdiscountamount_base")]
		public Microsoft.Xrm.Sdk.Money ManualDiscountAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("manualdiscountamount_base");
			}
		}
		
		/// <summary>
		/// Mostra quem atualizou o registro pela última vez.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data e hora de modificação do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Mostra quem atualizou o registro pela última vez em nome de outro usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Método de cobrança da linha de contrato do projeto. Os valores válidos são Hora, Material e Preço Fixo
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingmethod")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_BillingMethod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_billingmethod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BillingMethod");
				this.SetAttributeValue("msdyn_billingmethod", value);
				this.OnPropertyChanged("msdyn_BillingMethod");
			}
		}
		
		/// <summary>
		/// Selecione a data de início de cobrança da linha de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingstartdate")]
		public System.Nullable<System.DateTime> msdyn_BillingStartDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_billingstartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BillingStartDate");
				this.SetAttributeValue("msdyn_billingstartdate", value);
				this.OnPropertyChanged("msdyn_BillingStartDate");
			}
		}
		
		/// <summary>
		/// Selecione o status de cobrança para a linha de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_BillingStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_billingstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BillingStatus");
				this.SetAttributeValue("msdyn_billingstatus", value);
				this.OnPropertyChanged("msdyn_BillingStatus");
			}
		}
		
		/// <summary>
		/// Insira o valor que o cliente reservou ou deseja pagar pelo componente de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_budgetamount")]
		public Microsoft.Xrm.Sdk.Money msdyn_BudgetAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_budgetamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BudgetAmount");
				this.SetAttributeValue("msdyn_budgetamount", value);
				this.OnPropertyChanged("msdyn_BudgetAmount");
			}
		}
		
		/// <summary>
		/// Valor do campo Valor do Orçamento na moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_budgetamount_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_budgetamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_budgetamount_base");
			}
		}
		
		/// <summary>
		/// Mostra o preço de custo total do produto com base no preço de custo por unidade e quantidade.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_costamount")]
		public Microsoft.Xrm.Sdk.Money msdyn_CostAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_costamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_CostAmount");
				this.SetAttributeValue("msdyn_costamount", value);
				this.OnPropertyChanged("msdyn_CostAmount");
			}
		}
		
		/// <summary>
		/// Valor do campo Valor do Custo na moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_costamount_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_costamount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_costamount_base");
			}
		}
		
		/// <summary>
		/// Custo por unidade do produto. O padrão é o preço de custo do produto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_costpriceperunit")]
		public Microsoft.Xrm.Sdk.Money msdyn_CostPricePerUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_costpriceperunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_CostPricePerUnit");
				this.SetAttributeValue("msdyn_costpriceperunit", value);
				this.OnPropertyChanged("msdyn_CostPricePerUnit");
			}
		}
		
		/// <summary>
		/// Valor do campo Preço de Custo por Unidade na moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_costpriceperunit_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_costpriceperunit_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_costpriceperunit_base");
			}
		}
		
		/// <summary>
		/// Selecione se deseja incluir despesas na linha de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_includeexpense")]
		public System.Nullable<bool> msdyn_IncludeExpense
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_includeexpense");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_IncludeExpense");
				this.SetAttributeValue("msdyn_includeexpense", value);
				this.OnPropertyChanged("msdyn_IncludeExpense");
			}
		}
		
		/// <summary>
		/// Selecione se deseja incluir taxas na linha de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_includefee")]
		public System.Nullable<bool> msdyn_IncludeFee
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_includefee");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_IncludeFee");
				this.SetAttributeValue("msdyn_includefee", value);
				this.OnPropertyChanged("msdyn_IncludeFee");
			}
		}
		
		/// <summary>
		/// Selecione se deseja incluir materiais na linha de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_includematerial")]
		public System.Nullable<bool> msdyn_IncludeMaterial
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_includematerial");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_IncludeMaterial");
				this.SetAttributeValue("msdyn_includematerial", value);
				this.OnPropertyChanged("msdyn_IncludeMaterial");
			}
		}
		
		/// <summary>
		/// Selecione se deseja incluir transações de tempo na linha de contrato do projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_includetime")]
		public System.Nullable<bool> msdyn_IncludeTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_includetime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_IncludeTime");
				this.SetAttributeValue("msdyn_includetime", value);
				this.OnPropertyChanged("msdyn_IncludeTime");
			}
		}
		
		/// <summary>
		/// Selecione a frequência do trabalho de criação automática da fatura para criar a fatura.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_invoicefrequency")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_invoicefrequency
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_invoicefrequency");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_invoicefrequency");
				this.SetAttributeValue("msdyn_invoicefrequency", value);
				this.OnPropertyChanged("msdyn_invoicefrequency");
			}
		}
		
		/// <summary>
		/// O campo para distinguir as linhas de ordem do Project Service ou do Field Service
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_linetype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_LineType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_linetype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_LineType");
				this.SetAttributeValue("msdyn_linetype", value);
				this.OnPropertyChanged("msdyn_LineType");
			}
		}
		
		/// <summary>
		/// Selecione o projeto da linha de contrato de projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_project")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_project");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Project");
				this.SetAttributeValue("msdyn_project", value);
				this.OnPropertyChanged("msdyn_Project");
			}
		}
		
		/// <summary>
		/// (Preterido) Mostra a linha de cotação relacionada à linha de contrato de projeto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_quoteline")]
		public string msdyn_QuoteLine
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_quoteline");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_QuoteLine");
				this.SetAttributeValue("msdyn_quoteline", value);
				this.OnPropertyChanged("msdyn_QuoteLine");
			}
		}
		
		/// <summary>
		/// Data e hora da migração do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// ID do Proprietário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da unidade de negócios proprietária do registro
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da equipe que possui o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário proprietário do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Escolha o pacote principal associado a este produto
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbundleid")]
		public System.Nullable<System.Guid> ParentBundleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("parentbundleid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ParentBundleId");
				this.SetAttributeValue("parentbundleid", value);
				this.OnPropertyChanged("ParentBundleId");
			}
		}
		
		/// <summary>
		/// Escolha o pacote principal associado a este produto
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbundleidref")]
		public Microsoft.Xrm.Sdk.EntityReference ParentBundleIdRef
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentbundleidref");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ParentBundleIdRef");
				this.SetAttributeValue("parentbundleidref", value);
				this.OnPropertyChanged("ParentBundleIdRef");
			}
		}
		
		/// <summary>
		/// Digite o preço por unidade do produto da ordem. O padrão é o valor da lista de preços especificado na ordem para produtos existentes.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("priceperunit")]
		public Microsoft.Xrm.Sdk.Money PricePerUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("priceperunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PricePerUnit");
				this.SetAttributeValue("priceperunit", value);
				this.OnPropertyChanged("PricePerUnit");
			}
		}
		
		/// <summary>
		/// Valor do Preço por Unidade em moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("priceperunit_base")]
		public Microsoft.Xrm.Sdk.Money PricePerUnit_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("priceperunit_base");
			}
		}
		
		/// <summary>
		/// Escolha o tipo de erro de preço, como um produto ausente ou inválido ou quantidade ausente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PricingErrorCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PricingErrorCode");
				this.SetAttributeValue("pricingerrorcode", value);
				this.OnPropertyChanged("PricingErrorCode");
			}
		}
		
		/// <summary>
		/// O identificador exclusivo da associação do item da linha de produtos com pacote na ordem de venda.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productassociationid")]
		public System.Nullable<System.Guid> ProductAssociationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("productassociationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductAssociationId");
				this.SetAttributeValue("productassociationid", value);
				this.OnPropertyChanged("ProductAssociationId");
			}
		}
		
		/// <summary>
		/// Digite um nome ou uma descrição para identificar o tipo de produto fora do catálogo incluído na ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productdescription")]
		public string ProductDescription
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("productdescription");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductDescription");
				this.SetAttributeValue("productdescription", value);
				this.OnPropertyChanged("ProductDescription");
			}
		}
		
		/// <summary>
		/// Escolha o produto a ser incluído na ordem para vincular o preço do produto e outras informações à ordem primária.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
		public Microsoft.Xrm.Sdk.EntityReference ProductId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("productid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductId");
				this.SetAttributeValue("productid", value);
				this.OnPropertyChanged("ProductId");
			}
		}
		
		/// <summary>
		/// Campo calculado que será preenchido por nome e descrição do produto.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productname")]
		public string ProductName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("productname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductName");
				this.SetAttributeValue("productname", value);
				this.OnPropertyChanged("ProductName");
			}
		}
		
		/// <summary>
		/// Tipo de Produto
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("producttypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ProductTypeCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("producttypecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductTypeCode");
				this.SetAttributeValue("producttypecode", value);
				this.OnPropertyChanged("ProductTypeCode");
			}
		}
		
		/// <summary>
		/// Status da configuração da propriedade.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("propertyconfigurationstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue PropertyConfigurationStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("propertyconfigurationstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PropertyConfigurationStatus");
				this.SetAttributeValue("propertyconfigurationstatus", value);
				this.OnPropertyChanged("PropertyConfigurationStatus");
			}
		}
		
		/// <summary>
		/// Digite o valor ou a quantidade do produto solicitado pelo cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quantity")]
		public System.Nullable<decimal> Quantity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("quantity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Quantity");
				this.SetAttributeValue("quantity", value);
				this.OnPropertyChanged("Quantity");
			}
		}
		
		/// <summary>
		/// Digite o valor ou a quantidade do produto pendente da ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quantitybackordered")]
		public System.Nullable<decimal> QuantityBackordered
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("quantitybackordered");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("QuantityBackordered");
				this.SetAttributeValue("quantitybackordered", value);
				this.OnPropertyChanged("QuantityBackordered");
			}
		}
		
		/// <summary>
		/// Digite o valor ou a quantidade do produto que foi cancelado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quantitycancelled")]
		public System.Nullable<decimal> QuantityCancelled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("quantitycancelled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("QuantityCancelled");
				this.SetAttributeValue("quantitycancelled", value);
				this.OnPropertyChanged("QuantityCancelled");
			}
		}
		
		/// <summary>
		/// Digite o valor ou a quantidade do produto que foi enviado para a ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quantityshipped")]
		public System.Nullable<decimal> QuantityShipped
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("quantityshipped");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("QuantityShipped");
				this.SetAttributeValue("quantityshipped", value);
				this.OnPropertyChanged("QuantityShipped");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da Linha de Cotação associada à Linha da Ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quotedetailid")]
		public Microsoft.Xrm.Sdk.EntityReference QuoteDetailId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("quotedetailid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("QuoteDetailId");
				this.SetAttributeValue("quotedetailid", value);
				this.OnPropertyChanged("QuoteDetailId");
			}
		}
		
		/// <summary>
		/// Insira a data de entrega solicitada pelo cliente para o produto da ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("requestdeliveryby")]
		public System.Nullable<System.DateTime> RequestDeliveryBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("requestdeliveryby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("RequestDeliveryBy");
				this.SetAttributeValue("requestdeliveryby", value);
				this.OnPropertyChanged("RequestDeliveryBy");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do produto especificado na ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderdetailid")]
		public System.Nullable<System.Guid> SalesOrderDetailId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("salesorderdetailid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SalesOrderDetailId");
				this.SetAttributeValue("salesorderdetailid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("SalesOrderDetailId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderdetailid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SalesOrderDetailId = value;
			}
		}
		
		/// <summary>
		/// Nome de Detalhes do Pedido de Venda. Adicionado para Relacionamento referencial 1:n
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderdetailname")]
		public string SalesOrderDetailName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("salesorderdetailname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SalesOrderDetailName");
				this.SetAttributeValue("salesorderdetailname", value);
				this.OnPropertyChanged("SalesOrderDetailName");
			}
		}
		
		/// <summary>
		/// Mostra a ordem do produto. A ID é usada para vincular o preço e outros detalhes do produto aos valores totais e outras informações na ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
		public Microsoft.Xrm.Sdk.EntityReference SalesOrderId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("salesorderid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SalesOrderId");
				this.SetAttributeValue("salesorderid", value);
				this.OnPropertyChanged("SalesOrderId");
			}
		}
		
		/// <summary>
		/// Informa se o preço do produto está bloqueado para a ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderispricelocked")]
		public System.Nullable<bool> SalesOrderIsPriceLocked
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("salesorderispricelocked");
			}
		}
		
		/// <summary>
		/// Mostra o status da ordem à qual os detalhes da ordem estão associados.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderstatecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue SalesOrderStateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("salesorderstatecode");
			}
		}
		
		/// <summary>
		/// Escolha o usuário responsável pela venda do produto da ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesrepid")]
		public Microsoft.Xrm.Sdk.EntityReference SalesRepId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("salesrepid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SalesRepId");
				this.SetAttributeValue("salesrepid", value);
				this.OnPropertyChanged("SalesRepId");
			}
		}
		
		/// <summary>
		/// Mostra a ID dos dados que mantêm a sequência.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sequencenumber")]
		public System.Nullable<int> SequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("sequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SequenceNumber");
				this.SetAttributeValue("sequencenumber", value);
				this.OnPropertyChanged("SequenceNumber");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do endereço de entrega.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_addressid")]
		public System.Nullable<System.Guid> ShipTo_AddressId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("shipto_addressid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_AddressId");
				this.SetAttributeValue("shipto_addressid", value);
				this.OnPropertyChanged("ShipTo_AddressId");
			}
		}
		
		/// <summary>
		/// Digite a cidade do endereço para entrega do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_city")]
		public string ShipTo_City
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_city");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_City");
				this.SetAttributeValue("shipto_city", value);
				this.OnPropertyChanged("ShipTo_City");
			}
		}
		
		/// <summary>
		/// Digite o nome do contato principal no endereço para entrega do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_contactname")]
		public string ShipTo_ContactName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_contactname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_ContactName");
				this.SetAttributeValue("shipto_contactname", value);
				this.OnPropertyChanged("ShipTo_ContactName");
			}
		}
		
		/// <summary>
		/// Digite o país ou região do endereço para entrega do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_country")]
		public string ShipTo_Country
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_country");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Country");
				this.SetAttributeValue("shipto_country", value);
				this.OnPropertyChanged("ShipTo_Country");
			}
		}
		
		/// <summary>
		/// Digite o número do fax do endereço para entrega do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_fax")]
		public string ShipTo_Fax
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_fax");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Fax");
				this.SetAttributeValue("shipto_fax", value);
				this.OnPropertyChanged("ShipTo_Fax");
			}
		}
		
		/// <summary>
		/// Escolha as condições de frete para garantir que as ordens de entrega sejam processadas corretamente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShipTo_FreightTermsCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shipto_freighttermscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_FreightTermsCode");
				this.SetAttributeValue("shipto_freighttermscode", value);
				this.OnPropertyChanged("ShipTo_FreightTermsCode");
			}
		}
		
		/// <summary>
		/// Digite a primeira linha do endereço para remessa do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line1")]
		public string ShipTo_Line1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_line1");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Line1");
				this.SetAttributeValue("shipto_line1", value);
				this.OnPropertyChanged("ShipTo_Line1");
			}
		}
		
		/// <summary>
		/// Digite a segunda linha do endereço para remessa do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line2")]
		public string ShipTo_Line2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_line2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Line2");
				this.SetAttributeValue("shipto_line2", value);
				this.OnPropertyChanged("ShipTo_Line2");
			}
		}
		
		/// <summary>
		/// Digite a terceira linha do endereço para remessa.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_line3")]
		public string ShipTo_Line3
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_line3");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Line3");
				this.SetAttributeValue("shipto_line3", value);
				this.OnPropertyChanged("ShipTo_Line3");
			}
		}
		
		/// <summary>
		/// Digite um nome para o endereço de remessa do cliente, como "Matriz" ou "Escritório", para identificar o endereço.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_name")]
		public string ShipTo_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Name");
				this.SetAttributeValue("shipto_name", value);
				this.OnPropertyChanged("ShipTo_Name");
			}
		}
		
		/// <summary>
		/// Digite o CEP do endereço para remessa.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_postalcode")]
		public string ShipTo_PostalCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_postalcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_PostalCode");
				this.SetAttributeValue("shipto_postalcode", value);
				this.OnPropertyChanged("ShipTo_PostalCode");
			}
		}
		
		/// <summary>
		/// Digite o estado ou província do endereço para remessa.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_stateorprovince")]
		public string ShipTo_StateOrProvince
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_stateorprovince");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_StateOrProvince");
				this.SetAttributeValue("shipto_stateorprovince", value);
				this.OnPropertyChanged("ShipTo_StateOrProvince");
			}
		}
		
		/// <summary>
		/// Digite o número do telefone do endereço para remessa do cliente.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_telephone")]
		public string ShipTo_Telephone
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("shipto_telephone");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShipTo_Telephone");
				this.SetAttributeValue("shipto_telephone", value);
				this.OnPropertyChanged("ShipTo_Telephone");
			}
		}
		
		/// <summary>
		/// Digite o valor do imposto do produto da ordem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tax")]
		public Microsoft.Xrm.Sdk.Money Tax
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("tax");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Tax");
				this.SetAttributeValue("tax", value);
				this.OnPropertyChanged("Tax");
			}
		}
		
		/// <summary>
		/// Valor do Imposto em moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("tax_base")]
		public Microsoft.Xrm.Sdk.Money Tax_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("tax_base");
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Escolha a moeda local do registro para garantir que os orçamentos sejam relatados na moeda correta.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Escolha a unidade de medida para a quantidade de unidades base para esta compra, como cada ou dúzia.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uomid")]
		public Microsoft.Xrm.Sdk.EntityReference UoMId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("uomid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UoMId");
				this.SetAttributeValue("uomid", value);
				this.OnPropertyChanged("UoMId");
			}
		}
		
		/// <summary>
		/// Código de fuso horário em uso quando o registro foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Número da Versão
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Mostra o valor do desconto por unidade se um volume especificado for comprado. Configure descontos por volume no Catálogo de Produtos na área Configurações.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("volumediscountamount")]
		public Microsoft.Xrm.Sdk.Money VolumeDiscountAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("volumediscountamount");
			}
		}
		
		/// <summary>
		/// Valor do Desconto por Volume em moeda base.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("volumediscountamount_base")]
		public Microsoft.Xrm.Sdk.Money VolumeDiscountAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("volumediscountamount_base");
			}
		}
		
		/// <summary>
		/// Escolha se o produto da ordem deve ser enviado para o endereço especificado ou mantido até que o cliente ligue com instruções de coleta ou entrega adicionais.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("willcall")]
		public System.Nullable<bool> WillCall
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("willcall");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("WillCall");
				this.SetAttributeValue("willcall", value);
				this.OnPropertyChanged("WillCall");
			}
		}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_invoicedetail
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_invoicedetail")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.InvoiceDetail> msdyn_salesorderdetail_invoicedetail
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.InvoiceDetail>("msdyn_salesorderdetail_invoicedetail", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_invoicedetail");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.InvoiceDetail>("msdyn_salesorderdetail_invoicedetail", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_invoicedetail");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_actual
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_actual")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_actual> msdyn_salesorderdetail_msdyn_actual
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_actual>("msdyn_salesorderdetail_msdyn_actual", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_actual");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_actual>("msdyn_salesorderdetail_msdyn_actual", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_actual");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_contractlineinvoic
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_contractlineinvoic")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_contractlineinvoiceschedule> msdyn_salesorderdetail_msdyn_contractlineinvoic
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_contractlineinvoiceschedule>("msdyn_salesorderdetail_msdyn_contractlineinvoic", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_contractlineinvoic");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_contractlineinvoiceschedule>("msdyn_salesorderdetail_msdyn_contractlineinvoic", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_contractlineinvoic");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_contractlineschedu
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_contractlineschedu")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_contractlinescheduleofvalue> msdyn_salesorderdetail_msdyn_contractlineschedu
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_contractlinescheduleofvalue>("msdyn_salesorderdetail_msdyn_contractlineschedu", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_contractlineschedu");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_contractlinescheduleofvalue>("msdyn_salesorderdetail_msdyn_contractlineschedu", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_contractlineschedu");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_fact
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_fact")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_fact> msdyn_salesorderdetail_msdyn_fact
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_fact>("msdyn_salesorderdetail_msdyn_fact", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_fact");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_fact>("msdyn_salesorderdetail_msdyn_fact", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_fact");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_invoicelinetransac
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_invoicelinetransac")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_invoicelinetransaction> msdyn_salesorderdetail_msdyn_invoicelinetransac
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_invoicelinetransaction>("msdyn_salesorderdetail_msdyn_invoicelinetransac", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_invoicelinetransac");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_invoicelinetransaction>("msdyn_salesorderdetail_msdyn_invoicelinetransac", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_invoicelinetransac");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_journalline
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_journalline")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_journalline> msdyn_salesorderdetail_msdyn_journalline
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_journalline>("msdyn_salesorderdetail_msdyn_journalline", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_journalline");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_journalline>("msdyn_salesorderdetail_msdyn_journalline", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_journalline");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_orderlineresourcec
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_orderlineresourcec")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlineresourcecategory> msdyn_salesorderdetail_msdyn_orderlineresourcec
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlineresourcecategory>("msdyn_salesorderdetail_msdyn_orderlineresourcec", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_orderlineresourcec");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlineresourcecategory>("msdyn_salesorderdetail_msdyn_orderlineresourcec", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_orderlineresourcec");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_orderlinetransacti
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_orderlinetransacti")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransaction> msdyn_salesorderdetail_msdyn_orderlinetransacti
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransaction>("msdyn_salesorderdetail_msdyn_orderlinetransacti", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_orderlinetransacti");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransaction>("msdyn_salesorderdetail_msdyn_orderlinetransacti", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_orderlinetransacti");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_orderlinetranscat
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_orderlinetranscat")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransactioncategory> msdyn_salesorderdetail_msdyn_orderlinetranscat
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransactioncategory>("msdyn_salesorderdetail_msdyn_orderlinetranscat", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_orderlinetranscat");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransactioncategory>("msdyn_salesorderdetail_msdyn_orderlinetranscat", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_orderlinetranscat");
		//	}
		//}
		
		///// <summary>
		///// 1:N msdyn_salesorderdetail_msdyn_orderlinetransclas
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_salesorderdetail_msdyn_orderlinetransclas")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransactionclassification> msdyn_salesorderdetail_msdyn_orderlinetransclas
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransactionclassification>("msdyn_salesorderdetail_msdyn_orderlinetransclas", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_salesorderdetail_msdyn_orderlinetransclas");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_orderlinetransactionclassification>("msdyn_salesorderdetail_msdyn_orderlinetransclas", null, value);
		//		this.OnPropertyChanged("msdyn_salesorderdetail_msdyn_orderlinetransclas");
		//	}
		//}
		
		///// <summary>
		///// 1:N SalesOrderDetail_AsyncOperations
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrderDetail_AsyncOperations")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.AsyncOperation> SalesOrderDetail_AsyncOperations
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.AsyncOperation>("SalesOrderDetail_AsyncOperations", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SalesOrderDetail_AsyncOperations");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.AsyncOperation>("SalesOrderDetail_AsyncOperations", null, value);
		//		this.OnPropertyChanged("SalesOrderDetail_AsyncOperations");
		//	}
		//}
		
		///// <summary>
		///// 1:N SalesOrderDetail_BulkDeleteFailures
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrderDetail_BulkDeleteFailures")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.BulkDeleteFailure> SalesOrderDetail_BulkDeleteFailures
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.BulkDeleteFailure>("SalesOrderDetail_BulkDeleteFailures", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SalesOrderDetail_BulkDeleteFailures");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.BulkDeleteFailure>("SalesOrderDetail_BulkDeleteFailures", null, value);
		//		this.OnPropertyChanged("SalesOrderDetail_BulkDeleteFailures");
		//	}
		//}
		
		///// <summary>
		///// 1:N SalesOrderDetail_Dynamicpropertyinstance
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrderDetail_Dynamicpropertyinstance")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.DynamicPropertyInstance> SalesOrderDetail_Dynamicpropertyinstance
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.DynamicPropertyInstance>("SalesOrderDetail_Dynamicpropertyinstance", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SalesOrderDetail_Dynamicpropertyinstance");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.DynamicPropertyInstance>("SalesOrderDetail_Dynamicpropertyinstance", null, value);
		//		this.OnPropertyChanged("SalesOrderDetail_Dynamicpropertyinstance");
		//	}
		//}
		
		///// <summary>
		///// 1:N salesorderdetail_MailboxTrackingFolders
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorderdetail_MailboxTrackingFolders")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.MailboxTrackingFolder> salesorderdetail_MailboxTrackingFolders
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.MailboxTrackingFolder>("salesorderdetail_MailboxTrackingFolders", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("salesorderdetail_MailboxTrackingFolders");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.MailboxTrackingFolder>("salesorderdetail_MailboxTrackingFolders", null, value);
		//		this.OnPropertyChanged("salesorderdetail_MailboxTrackingFolders");
		//	}
		//}
		
		///// <summary>
		///// 1:N salesorderdetail_parent_salesorderdetail
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorderdetail_parent_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail> Referencedsalesorderdetail_parent_salesorderdetail
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parent_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Referencedsalesorderdetail_parent_salesorderdetail");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parent_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
		//		this.OnPropertyChanged("Referencedsalesorderdetail_parent_salesorderdetail");
		//	}
		//}
		
		///// <summary>
		///// 1:N salesorderdetail_parentref_salesorderdetail
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorderdetail_parentref_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail> Referencedsalesorderdetail_parentref_salesorderdetail
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parentref_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("Referencedsalesorderdetail_parentref_salesorderdetail");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parentref_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
		//		this.OnPropertyChanged("Referencedsalesorderdetail_parentref_salesorderdetail");
		//	}
		//}
		
		///// <summary>
		///// 1:N salesorderdetail_principalobjectattributeaccess
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorderdetail_principalobjectattributeaccess")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.PrincipalObjectAttributeAccess> salesorderdetail_principalobjectattributeaccess
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.PrincipalObjectAttributeAccess>("salesorderdetail_principalobjectattributeaccess", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("salesorderdetail_principalobjectattributeaccess");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.PrincipalObjectAttributeAccess>("salesorderdetail_principalobjectattributeaccess", null, value);
		//		this.OnPropertyChanged("salesorderdetail_principalobjectattributeaccess");
		//	}
		//}
		
		///// <summary>
		///// 1:N SalesOrderDetail_ProcessSessions
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrderDetail_ProcessSessions")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.ProcessSession> SalesOrderDetail_ProcessSessions
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.ProcessSession>("SalesOrderDetail_ProcessSessions", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SalesOrderDetail_ProcessSessions");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.ProcessSession>("SalesOrderDetail_ProcessSessions", null, value);
		//		this.OnPropertyChanged("SalesOrderDetail_ProcessSessions");
		//	}
		//}
		
		///// <summary>
		///// 1:N SalesOrderDetail_SyncErrors
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesOrderDetail_SyncErrors")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.SyncError> SalesOrderDetail_SyncErrors
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.SyncError>("SalesOrderDetail_SyncErrors", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("SalesOrderDetail_SyncErrors");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.SyncError>("SalesOrderDetail_SyncErrors", null, value);
		//		this.OnPropertyChanged("SalesOrderDetail_SyncErrors");
		//	}
		//}
		
		/// <summary>
		/// 1:N smt_salesorderdetail_quotedetail_lp_contract_line
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("smt_salesorderdetail_quotedetail_lp_contract_line")]
		public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.QuoteDetail> smt_salesorderdetail_quotedetail_lp_contract_line
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.QuoteDetail>("smt_salesorderdetail_quotedetail_lp_contract_line", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("smt_salesorderdetail_quotedetail_lp_contract_line");
				this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.QuoteDetail>("smt_salesorderdetail_quotedetail_lp_contract_line", null, value);
				this.OnPropertyChanged("smt_salesorderdetail_quotedetail_lp_contract_line");
			}
		}
		
		///// <summary>
		///// 1:N userentityinstancedata_salesorderdetail
		///// </summary>
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_salesorderdetail")]
		//public System.Collections.Generic.IEnumerable<CRM.Smart.ExtendedPSA.Extends.Earlybound.UserEntityInstanceData> userentityinstancedata_salesorderdetail
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.UserEntityInstanceData>("userentityinstancedata_salesorderdetail", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("userentityinstancedata_salesorderdetail");
		//		this.SetRelatedEntities<CRM.Smart.ExtendedPSA.Extends.Earlybound.UserEntityInstanceData>("userentityinstancedata_salesorderdetail", null, value);
		//		this.OnPropertyChanged("userentityinstancedata_salesorderdetail");
		//	}
		//}
		
		/// <summary>
		/// N:1 lk_salesorderdetail_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorderdetail_createdonbehalfby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_salesorderdetail_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_salesorderdetail_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_salesorderdetail_createdonbehalfby");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_salesorderdetail_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_salesorderdetail_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_salesorderdetail_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorderdetail_modifiedonbehalfby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_salesorderdetail_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_salesorderdetail_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_salesorderdetail_modifiedonbehalfby");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_salesorderdetail_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_salesorderdetail_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_salesorderdetailbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorderdetailbase_createdby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_salesorderdetailbase_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_salesorderdetailbase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_salesorderdetailbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesorderdetailbase_modifiedby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_salesorderdetailbase_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_salesorderdetailbase_modifiedby", null);
			}
		}
		
		///// <summary>
		///// N:1 msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_invoicefrequency")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_invoicefrequency msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_invoicefrequency>("msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_invoicefrequency>("msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency", null, value);
		//		this.OnPropertyChanged("msdyn_msdyn_invoicefrequency_salesorderdetail_invoicefrequency");
		//	}
		//}
		
		/// <summary>
		/// N:1 msdyn_msdyn_project_salesorderdetail_Project
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_project")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_project_salesorderdetail_Project")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_project msdyn_msdyn_project_salesorderdetail_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_project>("msdyn_msdyn_project_salesorderdetail_Project", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_project_salesorderdetail_Project");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.msdyn_project>("msdyn_msdyn_project_salesorderdetail_Project", null, value);
				this.OnPropertyChanged("msdyn_msdyn_project_salesorderdetail_Project");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_quotedetail_salesorderdetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("quotedetailid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_quotedetail_salesorderdetail")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.QuoteDetail msdyn_quotedetail_salesorderdetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.QuoteDetail>("msdyn_quotedetail_salesorderdetail", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_quotedetail_salesorderdetail");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.QuoteDetail>("msdyn_quotedetail_salesorderdetail", null, value);
				this.OnPropertyChanged("msdyn_quotedetail_salesorderdetail");
			}
		}
		
		/// <summary>
		/// N:1 order_details
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesorderid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("order_details")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrder order_details
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrder>("order_details", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("order_details");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrder>("order_details", null, value);
				this.OnPropertyChanged("order_details");
			}
		}
		
		///// <summary>
		///// N:1 product_order_details
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("product_order_details")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.Product product_order_details
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.Product>("product_order_details", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("product_order_details");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.Product>("product_order_details", null, value);
		//		this.OnPropertyChanged("product_order_details");
		//	}
		//}
		
		///// <summary>
		///// N:1 productAssociation_salesorder_details
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productassociationid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("productAssociation_salesorder_details")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.ProductAssociation productAssociation_salesorder_details
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.ProductAssociation>("productAssociation_salesorder_details", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("productAssociation_salesorder_details");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.ProductAssociation>("productAssociation_salesorder_details", null, value);
		//		this.OnPropertyChanged("productAssociation_salesorder_details");
		//	}
		//}
		
		/// <summary>
		/// N:1 salesorderdetail_parent_salesorderdetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbundleid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorderdetail_parent_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail Referencingsalesorderdetail_parent_salesorderdetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parent_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingsalesorderdetail_parent_salesorderdetail");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parent_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingsalesorderdetail_parent_salesorderdetail");
			}
		}
		
		/// <summary>
		/// N:1 salesorderdetail_parentref_salesorderdetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentbundleidref")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesorderdetail_parentref_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail Referencingsalesorderdetail_parentref_salesorderdetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parentref_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingsalesorderdetail_parentref_salesorderdetail");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SalesOrderDetail>("salesorderdetail_parentref_salesorderdetail", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingsalesorderdetail_parentref_salesorderdetail");
			}
		}
		
		/// <summary>
		/// N:1 system_user_salesorderdetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesrepid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("system_user_salesorderdetail")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser system_user_salesorderdetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("system_user_salesorderdetail", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("system_user_salesorderdetail");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("system_user_salesorderdetail", null, value);
				this.OnPropertyChanged("system_user_salesorderdetail");
			}
		}
		
		/// <summary>
		/// N:1 team_salesorderdetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_salesorderdetail")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.Team team_salesorderdetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.Team>("team_salesorderdetail", null);
			}
		}
		
		///// <summary>
		///// N:1 transactioncurrency_salesorderdetail
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("transactioncurrency_salesorderdetail")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.TransactionCurrency transactioncurrency_salesorderdetail
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.TransactionCurrency>("transactioncurrency_salesorderdetail", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("transactioncurrency_salesorderdetail");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.TransactionCurrency>("transactioncurrency_salesorderdetail", null, value);
		//		this.OnPropertyChanged("transactioncurrency_salesorderdetail");
		//	}
		//}
		
		///// <summary>
		///// N:1 unit_of_measurement_order_details
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uomid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("unit_of_measurement_order_details")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.UoM unit_of_measurement_order_details
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.UoM>("unit_of_measurement_order_details", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("unit_of_measurement_order_details");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.UoM>("unit_of_measurement_order_details", null, value);
		//		this.OnPropertyChanged("unit_of_measurement_order_details");
		//	}
		//}
		
		///// <summary>
		///// N:1 user_salesorderdetail
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_salesorderdetail")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser user_salesorderdetail
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("user_salesorderdetail", null);
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingmethod")]
		//public virtual msdyn_billingmethod? msdyn_BillingMethodEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((msdyn_billingmethod?)(EntityOptionSetEnum.GetEnum(this, "msdyn_billingmethod")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		msdyn_BillingMethod = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_billingstatus")]
		//public virtual msdyn_billingstatus? msdyn_BillingStatusEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((msdyn_billingstatus?)(EntityOptionSetEnum.GetEnum(this, "msdyn_billingstatus")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		msdyn_BillingStatus = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_linetype")]
		//public virtual msdyn_linetype? msdyn_LineTypeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((msdyn_linetype?)(EntityOptionSetEnum.GetEnum(this, "msdyn_linetype")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		msdyn_LineType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingerrorcode")]
		//public virtual Qooi_PricingErrorCode? PricingErrorCodeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((Qooi_PricingErrorCode?)(EntityOptionSetEnum.GetEnum(this, "pricingerrorcode")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		PricingErrorCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("producttypecode")]
		//public virtual QooiProduct_ProductType? ProductTypeCodeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((QooiProduct_ProductType?)(EntityOptionSetEnum.GetEnum(this, "producttypecode")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		ProductTypeCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("propertyconfigurationstatus")]
		//public virtual QooiProduct_PropertiesConfigurationStatus? PropertyConfigurationStatusEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((QooiProduct_PropertiesConfigurationStatus?)(EntityOptionSetEnum.GetEnum(this, "propertyconfigurationstatus")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		PropertyConfigurationStatus = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shipto_freighttermscode")]
		//public virtual SalesOrderDetail_ShipTo_FreightTermsCode? ShipTo_FreightTermsCodeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((SalesOrderDetail_ShipTo_FreightTermsCode?)(EntityOptionSetEnum.GetEnum(this, "shipto_freighttermscode")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		ShipTo_FreightTermsCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
	}
}