//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Smart.ExtendedPSA.Extends.Earlybound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum smt_holiday_requestState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("smt_holiday_request")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class smt_holiday_request : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string smt_bt_antecipation = "smt_bt_antecipation";
			public const string smt_dec_duration = "smt_dec_duration";
			public const string smt_dt_end = "smt_dt_end";
			public const string smt_dt_start = "smt_dt_start";
			public const string smt_holiday_requestId = "smt_holiday_requestid";
			public const string Id = "smt_holiday_requestid";
			public const string smt_int_days_quantity = "smt_int_days_quantity";
			public const string smt_int_duration = "smt_int_duration";
			public const string smt_int_quantity_days = "smt_int_quantity_days";
			public const string smt_lp_resource = "smt_lp_resource";
			public const string smt_name = "smt_name";
			public const string smt_smt_pl_type = "smt_smt_pl_type";
			public const string smt_st_justification = "smt_st_justification";
			public const string smt_tx_reason_antecipation = "smt_tx_reason_antecipation";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public smt_holiday_request() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "smt_holiday_request";
		
		public const string PrimaryIdAttribute = "smt_holiday_requestid";
		
		public const string PrimaryNameAttribute = "smt_name";
		
		public const int EntityTypeCode = 10325;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que criou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data e hora de criação do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que criou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Número de sequência da importação que criou este registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que modificou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data e hora de modificação do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que modificou o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Data e hora da migração do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// ID do Proprietário
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da unidade de negócios proprietária do registro
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da equipe que possui o registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário proprietário do registro.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Campo que informa se o tipo de solicitação é de adiantamento ou não.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_bt_antecipation")]
		public System.Nullable<bool> smt_bt_antecipation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("smt_bt_antecipation");
			}
			set
			{
				this.OnPropertyChanging("smt_bt_antecipation");
				this.SetAttributeValue("smt_bt_antecipation", value);
				this.OnPropertyChanged("smt_bt_antecipation");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_dec_duration")]
		public System.Nullable<decimal> smt_dec_duration
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("smt_dec_duration");
			}
			set
			{
				this.OnPropertyChanging("smt_dec_duration");
				this.SetAttributeValue("smt_dec_duration", value);
				this.OnPropertyChanged("smt_dec_duration");
			}
		}
		
		/// <summary>
		/// Campo que informa a data de término das férias solicitadas pelo usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_dt_end")]
		public System.Nullable<System.DateTime> smt_dt_end
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("smt_dt_end");
			}
			set
			{
				this.OnPropertyChanging("smt_dt_end");
				this.SetAttributeValue("smt_dt_end", value);
				this.OnPropertyChanged("smt_dt_end");
			}
		}
		
		/// <summary>
		/// Campo que informa a data inicial das férias que o usuário está solicitando.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_dt_start")]
		public System.Nullable<System.DateTime> smt_dt_start
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("smt_dt_start");
			}
			set
			{
				this.OnPropertyChanging("smt_dt_start");
				this.SetAttributeValue("smt_dt_start", value);
				this.OnPropertyChanged("smt_dt_start");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo de instâncias de entidade
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_holiday_requestid")]
		public System.Nullable<System.Guid> smt_holiday_requestId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("smt_holiday_requestid");
			}
			set
			{
				this.OnPropertyChanging("smt_holiday_requestId");
				this.SetAttributeValue("smt_holiday_requestid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("smt_holiday_requestId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_holiday_requestid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.smt_holiday_requestId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_int_days_quantity")]
		public System.Nullable<int> smt_int_days_quantity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("smt_int_days_quantity");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_int_duration")]
		public System.Nullable<int> smt_int_duration
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("smt_int_duration");
			}
			set
			{
				this.OnPropertyChanging("smt_int_duration");
				this.SetAttributeValue("smt_int_duration", value);
				this.OnPropertyChanged("smt_int_duration");
			}
		}
		
		/// <summary>
		/// Campo que informa a quantidade de dias das férias que o usuário está solicitando.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_int_quantity_days")]
		public System.Nullable<int> smt_int_quantity_days
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("smt_int_quantity_days");
			}
			set
			{
				this.OnPropertyChanging("smt_int_quantity_days");
				this.SetAttributeValue("smt_int_quantity_days", value);
				this.OnPropertyChanged("smt_int_quantity_days");
			}
		}
		
		/// <summary>
		/// Campo que informa o recurso que está solicitando as férias.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_lp_resource")]
		public Microsoft.Xrm.Sdk.EntityReference smt_lp_resource
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("smt_lp_resource");
			}
			set
			{
				this.OnPropertyChanging("smt_lp_resource");
				this.SetAttributeValue("smt_lp_resource", value);
				this.OnPropertyChanged("smt_lp_resource");
			}
		}
		
		/// <summary>
		/// O nome da entidade personalizada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_name")]
		public string smt_name
		{
			get
			{
				return this.GetAttributeValue<string>("smt_name");
			}
			set
			{
				this.OnPropertyChanging("smt_name");
				this.SetAttributeValue("smt_name", value);
				this.OnPropertyChanged("smt_name");
			}
		}
		
		/// <summary>
		/// Campo que informa qual o tipo de férias que o usuário está solicitando.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_smt_pl_type")]
		public Microsoft.Xrm.Sdk.OptionSetValue smt_smt_pl_type
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("smt_smt_pl_type");
			}
			set
			{
				this.OnPropertyChanging("smt_smt_pl_type");
				this.SetAttributeValue("smt_smt_pl_type", value);
				this.OnPropertyChanged("smt_smt_pl_type");
			}
		}
		
		/// <summary>
		/// Campo que informa o porquê que a solicitação de férias foi reprovada ou cancelada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_st_justification")]
		public string smt_st_justification
		{
			get
			{
				return this.GetAttributeValue<string>("smt_st_justification");
			}
			set
			{
				this.OnPropertyChanging("smt_st_justification");
				this.SetAttributeValue("smt_st_justification", value);
				this.OnPropertyChanged("smt_st_justification");
			}
		}
		
		/// <summary>
		/// Campo que informa o motivo da antecipação das férias.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_tx_reason_antecipation")]
		public string smt_tx_reason_antecipation
		{
			get
			{
				return this.GetAttributeValue<string>("smt_tx_reason_antecipation");
			}
			set
			{
				this.OnPropertyChanging("smt_tx_reason_antecipation");
				this.SetAttributeValue("smt_tx_reason_antecipation", value);
				this.OnPropertyChanged("smt_tx_reason_antecipation");
			}
		}
		
		/// <summary>
		/// Status de Solicitação de Férias
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<CRM.Smart.ExtendedPSA.Extends.Earlybound.smt_holiday_requestState> StateCodeSet
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((CRM.Smart.ExtendedPSA.Extends.Earlybound.smt_holiday_requestState)(System.Enum.ToObject(typeof(CRM.Smart.ExtendedPSA.Extends.Earlybound.smt_holiday_requestState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Razão do status de Solicitação de Férias
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}

        /// <summary>
        /// Razão do status de Solicitação de Férias
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
        public Microsoft.Xrm.Sdk.OptionSetValue statecode
        {
            get
            {
                return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
            }
            set
            {
                this.OnPropertyChanging("statecode");
                this.SetAttributeValue("statecode", value);
                this.OnPropertyChanged("statecode");
            }
        }

        /// <summary>
        /// Apenas para uso interno.
        /// </summary>
        [Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Código de fuso horário em uso quando o registro foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Número da Versão
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("smt_smt_pl_type")]
		public virtual smt_holiday_request_smt_smt_pl_type? smt_smt_pl_typeEnum
		{
			get
			{
				return ((smt_holiday_request_smt_smt_pl_type?)(EntityOptionSetEnum.GetEnum(this, "smt_smt_pl_type")));
			}
			set
			{
				smt_smt_pl_type = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual smt_holiday_request_StatusCode? StatusCodeEnum
		{
			get
			{
				return ((smt_holiday_request_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}