//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Smart.ExtendedPSA.Extends.Earlybound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum smt_holiday_request_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Aprovado = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelado = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enviado = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rascunho = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reprovado = 100000002,
	}
}