//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Smart.ExtendedPSA.Extends.Earlybound
{
	
	/// <summary>
	/// Configurações preferenciais do usuário.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("usersettings")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class UserSettings : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public UserSettings() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "usersettings";
		
		public const string PrimaryIdAttribute = "systemuserid";
		
		public const int EntityTypeCode = 150;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Frequência de sondagem normal usada para sincronização do catálogo de endereços no Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("addressbooksyncinterval")]
		public System.Nullable<int> AddressBookSyncInterval
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("addressbooksyncinterval");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AddressBookSyncInterval");
				this.SetAttributeValue("addressbooksyncinterval", value);
				this.OnPropertyChanged("AddressBookSyncInterval");
			}
		}
		
		/// <summary>
		/// Modo padrão (simples ou detalhado) da localização avançada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("advancedfindstartupmode")]
		public System.Nullable<int> AdvancedFindStartupMode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("advancedfindstartupmode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AdvancedFindStartupMode");
				this.SetAttributeValue("advancedfindstartupmode", value);
				this.OnPropertyChanged("AdvancedFindStartupMode");
			}
		}
		
		/// <summary>
		/// Este atributo não é mais usado. Os dados estão agora no atributo Mailbox.AllowEmailConnectorToUseCredentials.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowemailcredentials")]
		[System.ObsoleteAttribute()]
		public System.Nullable<bool> AllowEmailCredentials
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("allowemailcredentials");
			}
		}
		
		/// <summary>
		/// Designador AM a ser usado no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("amdesignator")]
		public string AMDesignator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("amdesignator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AMDesignator");
				this.SetAttributeValue("amdesignator", value);
				this.OnPropertyChanged("AMDesignator");
			}
		}
		
		/// <summary>
		/// Criar automaticamente contato na promoção do cliente
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("autocreatecontactonpromote")]
		public System.Nullable<int> AutoCreateContactOnPromote
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("autocreatecontactonpromote");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AutoCreateContactOnPromote");
				this.SetAttributeValue("autocreatecontactonpromote", value);
				this.OnPropertyChanged("AutoCreateContactOnPromote");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da unidade de negócios à qual o usuário está associado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		public System.Nullable<System.Guid> BusinessUnitId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("businessunitid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BusinessUnitId");
				this.SetAttributeValue("businessunitid", value);
				this.OnPropertyChanged("BusinessUnitId");
			}
		}
		
		/// <summary>
		/// Tipo de calendário do sistema. Por padrão, definido como Gregoriano (EUA).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("calendartype")]
		public System.Nullable<int> CalendarType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("calendartype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CalendarType");
				this.SetAttributeValue("calendartype", value);
				this.OnPropertyChanged("CalendarType");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que criou as configurações de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Data e hora em que o objeto de configurações de usuário foi criado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que criou o usersettings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Número de casas decimais que podem ser usadas para a moeda.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencydecimalprecision")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> CurrencyDecimalPrecision
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("currencydecimalprecision");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CurrencyDecimalPrecision");
				this.SetAttributeValue("currencydecimalprecision", value);
				this.OnPropertyChanged("CurrencyDecimalPrecision");
			}
		}
		
		/// <summary>
		/// Informações sobre como os símbolos de moeda são colocados no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencyformatcode")]
		public System.Nullable<int> CurrencyFormatCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("currencyformatcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CurrencyFormatCode");
				this.SetAttributeValue("currencyformatcode", value);
				this.OnPropertyChanged("CurrencyFormatCode");
			}
		}
		
		/// <summary>
		/// Símbolo usado para moeda no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("currencysymbol")]
		public string CurrencySymbol
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("currencysymbol");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CurrencySymbol");
				this.SetAttributeValue("currencysymbol", value);
				this.OnPropertyChanged("CurrencySymbol");
			}
		}
		
		/// <summary>
		/// Informação que especifica o nível de validação de dados em planilhas do Excel exportada em um formato adequado para importação.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datavalidationmodeforexporttoexcel")]
		public Microsoft.Xrm.Sdk.OptionSetValue DataValidationModeForExportToExcel
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("datavalidationmodeforexporttoexcel");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DataValidationModeForExportToExcel");
				this.SetAttributeValue("datavalidationmodeforexporttoexcel", value);
				this.OnPropertyChanged("DataValidationModeForExportToExcel");
			}
		}
		
		/// <summary>
		/// Informações sobre o modo de exibição de data no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateformatcode")]
		public System.Nullable<int> DateFormatCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dateformatcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DateFormatCode");
				this.SetAttributeValue("dateformatcode", value);
				this.OnPropertyChanged("DateFormatCode");
			}
		}
		
		/// <summary>
		/// Cadeia de caracteres mostrando como a data é exibida no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateformatstring")]
		public string DateFormatString
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dateformatstring");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DateFormatString");
				this.SetAttributeValue("dateformatstring", value);
				this.OnPropertyChanged("DateFormatString");
			}
		}
		
		/// <summary>
		/// Caractere usado para separar mês, dia e ano em datas do Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dateseparator")]
		public string DateSeparator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dateseparator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DateSeparator");
				this.SetAttributeValue("dateseparator", value);
				this.OnPropertyChanged("DateSeparator");
			}
		}
		
		/// <summary>
		/// Símbolo usado em casas decimais no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decimalsymbol")]
		public string DecimalSymbol
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("decimalsymbol");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DecimalSymbol");
				this.SetAttributeValue("decimalsymbol", value);
				this.OnPropertyChanged("DecimalSymbol");
			}
		}
		
		/// <summary>
		/// Modo de exibição de calendário padrão do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultcalendarview")]
		public System.Nullable<int> DefaultCalendarView
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defaultcalendarview");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DefaultCalendarView");
				this.SetAttributeValue("defaultcalendarview", value);
				this.OnPropertyChanged("DefaultCalendarView");
			}
		}
		
		/// <summary>
		/// Área de texto para inserir código de país padrão.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultcountrycode")]
		public string DefaultCountryCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("defaultcountrycode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DefaultCountryCode");
				this.SetAttributeValue("defaultcountrycode", value);
				this.OnPropertyChanged("DefaultCountryCode");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do painel padrão.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultdashboardid")]
		public System.Nullable<System.Guid> DefaultDashboardId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defaultdashboardid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DefaultDashboardId");
				this.SetAttributeValue("defaultdashboardid", value);
				this.OnPropertyChanged("DefaultDashboardId");
			}
		}
		
		/// <summary>
		/// Experiência de pesquisa padrão para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultsearchexperience")]
		public Microsoft.Xrm.Sdk.OptionSetValue DefaultSearchExperience
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("defaultsearchexperience");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DefaultSearchExperience");
				this.SetAttributeValue("defaultsearchexperience", value);
				this.OnPropertyChanged("DefaultSearchExperience");
			}
		}
		
		/// <summary>
		/// Este atributo não é mais usado. Os dados estão agora no atributo Mailbox.Password.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailpassword")]
		[System.ObsoleteAttribute()]
		public string EmailPassword
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("emailpassword");
			}
		}
		
		/// <summary>
		/// Este atributo não é mais usado. Os dados estão agora no atributo Mailbox.UserName.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailusername")]
		[System.ObsoleteAttribute()]
		public string EmailUsername
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("emailusername");
			}
		}
		
		/// <summary>
		/// Indica o modo de formulário a ser usado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityformmode")]
		public Microsoft.Xrm.Sdk.OptionSetValue EntityFormMode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("entityformmode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EntityFormMode");
				this.SetAttributeValue("entityformmode", value);
				this.OnPropertyChanged("EntityFormMode");
			}
		}
		
		/// <summary>
		/// Ordem na qual os nomes devem ser exibidos no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fullnameconventioncode")]
		public System.Nullable<int> FullNameConventionCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("fullnameconventioncode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FullNameConventionCode");
				this.SetAttributeValue("fullnameconventioncode", value);
				this.OnPropertyChanged("FullNameConventionCode");
			}
		}
		
		/// <summary>
		/// Informação que especifica se o painel Introdução está habilitado em listas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("getstartedpanecontentenabled")]
		public System.Nullable<bool> GetStartedPaneContentEnabled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("getstartedpanecontentenabled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("GetStartedPaneContentEnabled");
				this.SetAttributeValue("getstartedpanecontentenabled", value);
				this.OnPropertyChanged("GetStartedPaneContentEnabled");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do idioma da Ajuda.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("helplanguageid")]
		public System.Nullable<int> HelpLanguageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("helplanguageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("HelpLanguageId");
				this.SetAttributeValue("helplanguageid", value);
				this.OnPropertyChanged("HelpLanguageId");
			}
		}
		
		/// <summary>
		/// Home page do site para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagearea")]
		public string HomepageArea
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("homepagearea");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("HomepageArea");
				this.SetAttributeValue("homepagearea", value);
				this.OnPropertyChanged("HomepageArea");
			}
		}
		
		/// <summary>
		/// Configuração do layout da página inicial.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagelayout")]
		public string HomepageLayout
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("homepagelayout");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("HomepageLayout");
				this.SetAttributeValue("homepagelayout", value);
				this.OnPropertyChanged("HomepageLayout");
			}
		}
		
		/// <summary>
		/// Página do site para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("homepagesubarea")]
		public string HomepageSubarea
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("homepagesubarea");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("HomepageSubarea");
				this.SetAttributeValue("homepagesubarea", value);
				this.OnPropertyChanged("HomepageSubarea");
			}
		}
		
		/// <summary>
		/// Informações que especificam se uma conta de usuário deve ignorar emails não solicitados (obsoletos).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ignoreunsolicitedemail")]
		public System.Nullable<bool> IgnoreUnsolicitedEmail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ignoreunsolicitedemail");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IgnoreUnsolicitedEmail");
				this.SetAttributeValue("ignoreunsolicitedemail", value);
				this.OnPropertyChanged("IgnoreUnsolicitedEmail");
			}
		}
		
		/// <summary>
		/// Método de filtragem de emails de entrada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemailfilteringmethod")]
		public Microsoft.Xrm.Sdk.OptionSetValue IncomingEmailFilteringMethod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("incomingemailfilteringmethod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IncomingEmailFilteringMethod");
				this.SetAttributeValue("incomingemailfilteringmethod", value);
				this.OnPropertyChanged("IncomingEmailFilteringMethod");
			}
		}
		
		/// <summary>
		/// Mostra ou descarta o alerta de Aplicativos para Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isappsforcrmalertdismissed")]
		public System.Nullable<bool> IsAppsForCrmAlertDismissed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isappsforcrmalertdismissed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsAppsForCrmAlertDismissed");
				this.SetAttributeValue("isappsforcrmalertdismissed", value);
				this.OnPropertyChanged("IsAppsForCrmAlertDismissed");
			}
		}
		
		/// <summary>
		/// Indica se o recurso Captura Automática será usado habilitado ou não.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isautodatacaptureenabled")]
		public System.Nullable<bool> IsAutoDataCaptureEnabled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isautodatacaptureenabled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsAutoDataCaptureEnabled");
				this.SetAttributeValue("isautodatacaptureenabled", value);
				this.OnPropertyChanged("IsAutoDataCaptureEnabled");
			}
		}
		
		/// <summary>
		/// Habilitar ou desabilitar seleção do código de país.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefaultcountrycodecheckenabled")]
		public System.Nullable<bool> IsDefaultCountryCodeCheckEnabled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefaultcountrycodecheckenabled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsDefaultCountryCodeCheckEnabled");
				this.SetAttributeValue("isdefaultcountrycodecheckenabled", value);
				this.OnPropertyChanged("IsDefaultCountryCodeCheckEnabled");
			}
		}
		
		/// <summary>
		/// Indica se a detecção de duplicidade é habilitada ao entrar online.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isduplicatedetectionenabledwhengoingonline")]
		public System.Nullable<bool> IsDuplicateDetectionEnabledWhenGoingOnline
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isduplicatedetectionenabledwhengoingonline");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsDuplicateDetectionEnabledWhenGoingOnline");
				this.SetAttributeValue("isduplicatedetectionenabledwhengoingonline", value);
				this.OnPropertyChanged("IsDuplicateDetectionEnabledWhenGoingOnline");
			}
		}
		
		/// <summary>
		/// Habilitar ou desabilitar a ajuda guiada.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isguidedhelpenabled")]
		public System.Nullable<bool> IsGuidedHelpEnabled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isguidedhelpenabled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsGuidedHelpEnabled");
				this.SetAttributeValue("isguidedhelpenabled", value);
				this.OnPropertyChanged("IsGuidedHelpEnabled");
			}
		}
		
		/// <summary>
		/// Indica se a sincronização da reserva de recursos do usuário com o Exchange é habilitada no nível do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isresourcebookingexchangesyncenabled")]
		public System.Nullable<bool> IsResourceBookingExchangeSyncEnabled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isresourcebookingexchangesyncenabled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsResourceBookingExchangeSyncEnabled");
				this.SetAttributeValue("isresourcebookingexchangesyncenabled", value);
				this.OnPropertyChanged("IsResourceBookingExchangeSyncEnabled");
			}
		}
		
		/// <summary>
		/// Indica se o privilégio enviar como outro usuário está habilitado ou não.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issendasallowed")]
		public System.Nullable<bool> IsSendAsAllowed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("issendasallowed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsSendAsAllowed");
				this.SetAttributeValue("issendasallowed", value);
				this.OnPropertyChanged("IsSendAsAllowed");
			}
		}
		
		/// <summary>
		/// Mostra a última vez que os rastreamentos foram lidos no banco de dados.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastalertsviewedtime")]
		public System.Nullable<System.DateTime> LastAlertsViewedTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastalertsviewedtime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("LastAlertsViewedTime");
				this.SetAttributeValue("lastalertsviewedtime", value);
				this.OnPropertyChanged("LastAlertsViewedTime");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da localidade do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("localeid")]
		public System.Nullable<int> LocaleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("localeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("LocaleId");
				this.SetAttributeValue("localeid", value);
				this.OnPropertyChanged("LocaleId");
			}
		}
		
		/// <summary>
		/// Informação que especifica como a Data por Extenso é exibida no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("longdateformatcode")]
		public System.Nullable<int> LongDateFormatCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("longdateformatcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("LongDateFormatCode");
				this.SetAttributeValue("longdateformatcode", value);
				this.OnPropertyChanged("LongDateFormatCode");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário que modificou por último as configurações de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Data e hora da última modificação do objeto de configurações de usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário delegado que modificou o usersettings pela última vez.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Informação que especifica como os números negativos de moeda são exibidos no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("negativecurrencyformatcode")]
		public System.Nullable<int> NegativeCurrencyFormatCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("negativecurrencyformatcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("NegativeCurrencyFormatCode");
				this.SetAttributeValue("negativecurrencyformatcode", value);
				this.OnPropertyChanged("NegativeCurrencyFormatCode");
			}
		}
		
		/// <summary>
		/// Informação que especifica como os números negativos são exibidos no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("negativeformatcode")]
		public System.Nullable<int> NegativeFormatCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("negativeformatcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("NegativeFormatCode");
				this.SetAttributeValue("negativeformatcode", value);
				this.OnPropertyChanged("NegativeFormatCode");
			}
		}
		
		/// <summary>
		/// Próximo número de controle.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nexttrackingnumber")]
		public System.Nullable<int> NextTrackingNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("nexttrackingnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("NextTrackingNumber");
				this.SetAttributeValue("nexttrackingnumber", value);
				this.OnPropertyChanged("NextTrackingNumber");
			}
		}
		
		/// <summary>
		/// Informação que especifica como os números são agrupados no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numbergroupformat")]
		public string NumberGroupFormat
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("numbergroupformat");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("NumberGroupFormat");
				this.SetAttributeValue("numbergroupformat", value);
				this.OnPropertyChanged("NumberGroupFormat");
			}
		}
		
		/// <summary>
		/// Símbolo usado para separação de números no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberseparator")]
		public string NumberSeparator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("numberseparator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("NumberSeparator");
				this.SetAttributeValue("numberseparator", value);
				this.OnPropertyChanged("NumberSeparator");
			}
		}
		
		/// <summary>
		/// Frequência de sondagem normal usada para sincronização offline em segundo plano no Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("offlinesyncinterval")]
		public System.Nullable<int> OfflineSyncInterval
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("offlinesyncinterval");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OfflineSyncInterval");
				this.SetAttributeValue("offlinesyncinterval", value);
				this.OnPropertyChanged("OfflineSyncInterval");
			}
		}
		
		/// <summary>
		/// Frequência de pesquisa normal usada na sincronização de registros no Microsoft Office Outlook.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("outlooksyncinterval")]
		public System.Nullable<int> OutlookSyncInterval
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("outlooksyncinterval");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OutlookSyncInterval");
				this.SetAttributeValue("outlooksyncinterval", value);
				this.OnPropertyChanged("OutlookSyncInterval");
			}
		}
		
		/// <summary>
		/// Informação que especifica o número de itens a serem listados em uma página no modo de exibição de lista.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("paginglimit")]
		public System.Nullable<int> PagingLimit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("paginglimit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PagingLimit");
				this.SetAttributeValue("paginglimit", value);
				this.OnPropertyChanged("PagingLimit");
			}
		}
		
		/// <summary>
		/// Apenas para uso interno.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("personalizationsettings")]
		public string PersonalizationSettings
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("personalizationsettings");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PersonalizationSettings");
				this.SetAttributeValue("personalizationsettings", value);
				this.OnPropertyChanged("PersonalizationSettings");
			}
		}
		
		/// <summary>
		/// Designador PM a ser usado no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pmdesignator")]
		public string PMDesignator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("pmdesignator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PMDesignator");
				this.SetAttributeValue("pmdesignator", value);
				this.OnPropertyChanged("PMDesignator");
			}
		}
		
		/// <summary>
		/// Número de casas decimais que podem ser usadas em preços.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pricingdecimalprecision")]
		[System.ObsoleteAttribute()]
		public System.Nullable<int> PricingDecimalPrecision
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pricingdecimalprecision");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PricingDecimalPrecision");
				this.SetAttributeValue("pricingdecimalprecision", value);
				this.OnPropertyChanged("PricingDecimalPrecision");
			}
		}
		
		/// <summary>
		/// Lista de opções para selecionar a preferência do usuário ao informar erros de script.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("reportscripterrors")]
		public Microsoft.Xrm.Sdk.OptionSetValue ReportScriptErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("reportscripterrors");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ReportScriptErrors");
				this.SetAttributeValue("reportscripterrors", value);
				this.OnPropertyChanged("ReportScriptErrors");
			}
		}
		
		/// <summary>
		/// O número da versão da sincronização de reservas de recursos com o Exchange.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resourcebookingexchangesyncversion")]
		public System.Nullable<long> ResourceBookingExchangeSyncVersion
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("resourcebookingexchangesyncversion");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ResourceBookingExchangeSyncVersion");
				this.SetAttributeValue("resourcebookingexchangesyncversion", value);
				this.OnPropertyChanged("ResourceBookingExchangeSyncVersion");
			}
		}
		
		/// <summary>
		/// Armazena a ID do filtro salvo do painel de hub do SAC selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("selectedglobalfilterid")]
		public System.Nullable<System.Guid> SelectedGlobalFilterId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("selectedglobalfilterid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SelectedGlobalFilterId");
				this.SetAttributeValue("selectedglobalfilterid", value);
				this.OnPropertyChanged("SelectedGlobalFilterId");
			}
		}
		
		/// <summary>
		/// Informação que especifica se o número da semana deve ser mostrado em exibições de calendário no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("showweeknumber")]
		public System.Nullable<bool> ShowWeekNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("showweeknumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ShowWeekNumber");
				this.SetAttributeValue("showweeknumber", value);
				this.OnPropertyChanged("ShowWeekNumber");
			}
		}
		
		/// <summary>
		/// Somente para uso Interno
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("splitviewstate")]
		public System.Nullable<bool> SplitViewState
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("splitviewstate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SplitViewState");
				this.SetAttributeValue("splitviewstate", value);
				this.OnPropertyChanged("SplitViewState");
			}
		}
		
		/// <summary>
		/// Indica se o campo da empresa nos itens do Outlook é definido durante a sincronização do programa.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("synccontactcompany")]
		public System.Nullable<bool> SyncContactCompany
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("synccontactcompany");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SyncContactCompany");
				this.SetAttributeValue("synccontactcompany", value);
				this.OnPropertyChanged("SyncContactCompany");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public System.Nullable<System.Guid> SystemUserId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("systemuserid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SystemUserId");
				this.SetAttributeValue("systemuserid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("SystemUserId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SystemUserId = value;
			}
		}
		
		/// <summary>
		/// Informação que especifica como a hora é exibida no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeformatcode")]
		public System.Nullable<int> TimeFormatCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timeformatcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeFormatCode");
				this.SetAttributeValue("timeformatcode", value);
				this.OnPropertyChanged("TimeFormatCode");
			}
		}
		
		/// <summary>
		/// Texto do modo de exibição de hora no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeformatstring")]
		public string TimeFormatString
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("timeformatstring");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeFormatString");
				this.SetAttributeValue("timeformatstring", value);
				this.OnPropertyChanged("TimeFormatString");
			}
		}
		
		/// <summary>
		/// Texto do modo de exibição de hora no Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timeseparator")]
		public string TimeSeparator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("timeseparator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeSeparator");
				this.SetAttributeValue("timeseparator", value);
				this.OnPropertyChanged("TimeSeparator");
			}
		}
		
		/// <summary>
		/// Ajuste do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonebias")]
		public System.Nullable<int> TimeZoneBias
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonebias");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneBias");
				this.SetAttributeValue("timezonebias", value);
				this.OnPropertyChanged("TimeZoneBias");
			}
		}
		
		/// <summary>
		/// Fuso horário local do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonecode")]
		public System.Nullable<int> TimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneCode");
				this.SetAttributeValue("timezonecode", value);
				this.OnPropertyChanged("TimeZoneCode");
			}
		}
		
		/// <summary>
		/// Ajuste do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightbias")]
		public System.Nullable<int> TimeZoneDaylightBias
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightbias");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightBias");
				this.SetAttributeValue("timezonedaylightbias", value);
				this.OnPropertyChanged("TimeZoneDaylightBias");
			}
		}
		
		/// <summary>
		/// Dia do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightday")]
		public System.Nullable<int> TimeZoneDaylightDay
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightday");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightDay");
				this.SetAttributeValue("timezonedaylightday", value);
				this.OnPropertyChanged("TimeZoneDaylightDay");
			}
		}
		
		/// <summary>
		/// Dia da semana do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightdayofweek")]
		public System.Nullable<int> TimeZoneDaylightDayOfWeek
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightdayofweek");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightDayOfWeek");
				this.SetAttributeValue("timezonedaylightdayofweek", value);
				this.OnPropertyChanged("TimeZoneDaylightDayOfWeek");
			}
		}
		
		/// <summary>
		/// Hora do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylighthour")]
		public System.Nullable<int> TimeZoneDaylightHour
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylighthour");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightHour");
				this.SetAttributeValue("timezonedaylighthour", value);
				this.OnPropertyChanged("TimeZoneDaylightHour");
			}
		}
		
		/// <summary>
		/// Minuto do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightminute")]
		public System.Nullable<int> TimeZoneDaylightMinute
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightminute");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightMinute");
				this.SetAttributeValue("timezonedaylightminute", value);
				this.OnPropertyChanged("TimeZoneDaylightMinute");
			}
		}
		
		/// <summary>
		/// Mês do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightmonth")]
		public System.Nullable<int> TimeZoneDaylightMonth
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightmonth");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightMonth");
				this.SetAttributeValue("timezonedaylightmonth", value);
				this.OnPropertyChanged("TimeZoneDaylightMonth");
			}
		}
		
		/// <summary>
		/// Segundo do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightsecond")]
		public System.Nullable<int> TimeZoneDaylightSecond
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightsecond");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightSecond");
				this.SetAttributeValue("timezonedaylightsecond", value);
				this.OnPropertyChanged("TimeZoneDaylightSecond");
			}
		}
		
		/// <summary>
		/// Ano do horário de verão do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonedaylightyear")]
		public System.Nullable<int> TimeZoneDaylightYear
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonedaylightyear");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneDaylightYear");
				this.SetAttributeValue("timezonedaylightyear", value);
				this.OnPropertyChanged("TimeZoneDaylightYear");
			}
		}
		
		/// <summary>
		/// Diferença do horário oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardbias")]
		public System.Nullable<int> TimeZoneStandardBias
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardbias");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardBias");
				this.SetAttributeValue("timezonestandardbias", value);
				this.OnPropertyChanged("TimeZoneStandardBias");
			}
		}
		
		/// <summary>
		/// Dia oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardday")]
		public System.Nullable<int> TimeZoneStandardDay
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardday");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardDay");
				this.SetAttributeValue("timezonestandardday", value);
				this.OnPropertyChanged("TimeZoneStandardDay");
			}
		}
		
		/// <summary>
		/// Dia da semana oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandarddayofweek")]
		public System.Nullable<int> TimeZoneStandardDayOfWeek
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandarddayofweek");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardDayOfWeek");
				this.SetAttributeValue("timezonestandarddayofweek", value);
				this.OnPropertyChanged("TimeZoneStandardDayOfWeek");
			}
		}
		
		/// <summary>
		/// Hora oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardhour")]
		public System.Nullable<int> TimeZoneStandardHour
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardhour");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardHour");
				this.SetAttributeValue("timezonestandardhour", value);
				this.OnPropertyChanged("TimeZoneStandardHour");
			}
		}
		
		/// <summary>
		/// Minuto oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardminute")]
		public System.Nullable<int> TimeZoneStandardMinute
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardminute");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardMinute");
				this.SetAttributeValue("timezonestandardminute", value);
				this.OnPropertyChanged("TimeZoneStandardMinute");
			}
		}
		
		/// <summary>
		/// Mês oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardmonth")]
		public System.Nullable<int> TimeZoneStandardMonth
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardmonth");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardMonth");
				this.SetAttributeValue("timezonestandardmonth", value);
				this.OnPropertyChanged("TimeZoneStandardMonth");
			}
		}
		
		/// <summary>
		/// Segundo oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardsecond")]
		public System.Nullable<int> TimeZoneStandardSecond
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardsecond");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardSecond");
				this.SetAttributeValue("timezonestandardsecond", value);
				this.OnPropertyChanged("TimeZoneStandardSecond");
			}
		}
		
		/// <summary>
		/// Ano oficial do fuso horário local do usuário. Calculado pelo sistema com base no fuso horário selecionado.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezonestandardyear")]
		public System.Nullable<int> TimeZoneStandardYear
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezonestandardyear");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneStandardYear");
				this.SetAttributeValue("timezonestandardyear", value);
				this.OnPropertyChanged("TimeZoneStandardYear");
			}
		}
		
		/// <summary>
		/// ID de token de controle.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("trackingtokenid")]
		public System.Nullable<int> TrackingTokenId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("trackingtokenid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TrackingTokenId");
				this.SetAttributeValue("trackingtokenid", value);
				this.OnPropertyChanged("TrackingTokenId");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo da moeda padrão do usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Identificador exclusivo do idioma no qual a interface do usuário é exibida.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uilanguageid")]
		public System.Nullable<int> UILanguageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("uilanguageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UILanguageId");
				this.SetAttributeValue("uilanguageid", value);
				this.OnPropertyChanged("UILanguageId");
			}
		}
		
		/// <summary>
		/// Indica se o formulário de compromisso do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novos compromissos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforappointment")]
		public System.Nullable<bool> UseCrmFormForAppointment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforappointment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UseCrmFormForAppointment");
				this.SetAttributeValue("usecrmformforappointment", value);
				this.OnPropertyChanged("UseCrmFormForAppointment");
			}
		}
		
		/// <summary>
		/// Indica se o formulário de contatos do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novos contatos.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforcontact")]
		public System.Nullable<bool> UseCrmFormForContact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforcontact");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UseCrmFormForContact");
				this.SetAttributeValue("usecrmformforcontact", value);
				this.OnPropertyChanged("UseCrmFormForContact");
			}
		}
		
		/// <summary>
		/// Indica se o formulário de email do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novos emails.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformforemail")]
		public System.Nullable<bool> UseCrmFormForEmail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformforemail");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UseCrmFormForEmail");
				this.SetAttributeValue("usecrmformforemail", value);
				this.OnPropertyChanged("UseCrmFormForEmail");
			}
		}
		
		/// <summary>
		/// Indica se o formulário de tarefa do Microsoft Dynamics 365 no Microsoft Office Outlook deve ser usado para criar novas tarefas.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("usecrmformfortask")]
		public System.Nullable<bool> UseCrmFormForTask
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("usecrmformfortask");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UseCrmFormForTask");
				this.SetAttributeValue("usecrmformfortask", value);
				this.OnPropertyChanged("UseCrmFormForTask");
			}
		}
		
		/// <summary>
		/// Indica se faixas de imagem são usadas para processar imagens.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("useimagestrips")]
		public System.Nullable<bool> UseImageStrips
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("useimagestrips");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UseImageStrips");
				this.SetAttributeValue("useimagestrips", value);
				this.OnPropertyChanged("UseImageStrips");
			}
		}
		
		/// <summary>
		/// Especifica as IDs de perfil de usuário em uma lista separada por vírgula.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("userprofile")]
		public string UserProfile
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("userprofile");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UserProfile");
				this.SetAttributeValue("userprofile", value);
				this.OnPropertyChanged("UserProfile");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// O layout do painel de visualização.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("visualizationpanelayout")]
		public Microsoft.Xrm.Sdk.OptionSetValue VisualizationPaneLayout
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("visualizationpanelayout");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("VisualizationPaneLayout");
				this.SetAttributeValue("visualizationpanelayout", value);
				this.OnPropertyChanged("VisualizationPaneLayout");
			}
		}
		
		/// <summary>
		/// Hora de início do dia útil para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workdaystarttime")]
		public string WorkdayStartTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("workdaystarttime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("WorkdayStartTime");
				this.SetAttributeValue("workdaystarttime", value);
				this.OnPropertyChanged("WorkdayStartTime");
			}
		}
		
		/// <summary>
		/// Hora de término do dia útil para o usuário.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workdaystoptime")]
		public string WorkdayStopTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("workdaystoptime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("WorkdayStopTime");
				this.SetAttributeValue("workdaystoptime", value);
				this.OnPropertyChanged("WorkdayStopTime");
			}
		}
		
		///// <summary>
		///// N:1 business_unit_user_settings
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businessunitid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_user_settings")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.BusinessUnit business_unit_user_settings
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.BusinessUnit>("business_unit_user_settings", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("business_unit_user_settings");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.BusinessUnit>("business_unit_user_settings", null, value);
		//		this.OnPropertyChanged("business_unit_user_settings");
		//	}
		//}
		
		/// <summary>
		/// N:1 lk_usersettings_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettings_createdonbehalfby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_usersettings_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_usersettings_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_usersettings_createdonbehalfby");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_usersettings_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_usersettings_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettings_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettings_modifiedonbehalfby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_usersettings_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_usersettings_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_usersettings_modifiedonbehalfby");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_usersettings_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_usersettings_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettingsbase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettingsbase_createdby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_usersettingsbase_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_usersettingsbase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_usersettingsbase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_usersettingsbase_modifiedby")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser lk_usersettingsbase_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("lk_usersettingsbase_modifiedby", null);
			}
		}
		
		///// <summary>
		///// N:1 transactioncurrency_usersettings
		///// </summary>
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		//[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("transactioncurrency_usersettings")]
		//public CRM.Smart.ExtendedPSA.Extends.Earlybound.TransactionCurrency transactioncurrency_usersettings
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.TransactionCurrency>("transactioncurrency_usersettings", null);
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		this.OnPropertyChanging("transactioncurrency_usersettings");
		//		this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.TransactionCurrency>("transactioncurrency_usersettings", null, value);
		//		this.OnPropertyChanged("transactioncurrency_usersettings");
		//	}
		//}
		
		/// <summary>
		/// N:1 user_settings
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_settings")]
		public CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser user_settings
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("user_settings", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_settings");
				this.SetRelatedEntity<CRM.Smart.ExtendedPSA.Extends.Earlybound.SystemUser>("user_settings", null, value);
				this.OnPropertyChanged("user_settings");
			}
		}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datavalidationmodeforexporttoexcel")]
		//public virtual UserSettings_DataValidationModeForExportToExcel? DataValidationModeForExportToExcelEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((UserSettings_DataValidationModeForExportToExcel?)(EntityOptionSetEnum.GetEnum(this, "datavalidationmodeforexporttoexcel")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		DataValidationModeForExportToExcel = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaultsearchexperience")]
		//public virtual UserSettings_DefaultSearchExperience? DefaultSearchExperienceEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((UserSettings_DefaultSearchExperience?)(EntityOptionSetEnum.GetEnum(this, "defaultsearchexperience")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		DefaultSearchExperience = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityformmode")]
		//public virtual UserSettings_EntityFormMode? EntityFormModeEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((UserSettings_EntityFormMode?)(EntityOptionSetEnum.GetEnum(this, "entityformmode")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		EntityFormMode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incomingemailfilteringmethod")]
		//public virtual UserSettings_IncomingEmailFilteringMethod? IncomingEmailFilteringMethodEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((UserSettings_IncomingEmailFilteringMethod?)(EntityOptionSetEnum.GetEnum(this, "incomingemailfilteringmethod")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		IncomingEmailFilteringMethod = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("reportscripterrors")]
		//public virtual UserSettings_ReportScriptErrors? ReportScriptErrorsEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((UserSettings_ReportScriptErrors?)(EntityOptionSetEnum.GetEnum(this, "reportscripterrors")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		ReportScriptErrors = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
		
		//[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("visualizationpanelayout")]
		//public virtual UserSettings_VisualizationPaneLayout? VisualizationPaneLayoutEnum
		//{
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	get
		//	{
		//		return ((UserSettings_VisualizationPaneLayout?)(EntityOptionSetEnum.GetEnum(this, "visualizationpanelayout")));
		//	}
		//	[System.Diagnostics.DebuggerNonUserCode()]
		//	set
		//	{
		//		VisualizationPaneLayout = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
		//	}
		//}
	}
}